### ISSUE TITLE
Bug: No way to style `<video>` element inside `<mux-video>`

### ISSUE THREAD

**Issue by balexand** [muxinc/elements#125]
### Which Mux Elements/Packages has a bug?

- mux-video

### Which browser(s) are you using?

- Chrome

### Which operating system(s) are you using?

Mac

### How are you using Mux Elements?

`<script async src="https://unpkg.com/@mux-elements/mux-video"></script>`.

### Describe the bug

I want to style the`<video>` element inside of the `<mux-video>` element. In particular, I'd like to add `object-fit: cover`.

<img width="842" alt="Pasted_Image_3_8_22__2_30_PM" src="https://user-images.githubusercontent.com/181187/157328435-22788f9e-dc1c-495f-941c-996d0970fa11.png">

## The current behavior

As far as I can tell, there is no way to style this element.

## The expected behavior

I want to be able to style it. A simple solution would be to put a `part="video"` attribute on the `<video>` element. That way one could style it as described in https://developer.mozilla.org/en-US/docs/Web/CSS/::part. I've tested this out by adding the `part` attribute in Chrome Devtools and it works.

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/181187/157329039-a17db9f8-8531-45a0-b1b7-b103d35bfc71.png">

**Comment by luwes** [comment]
thanks for the feedback @balexand! this seems like a good solution, we'll discuss and come back to you.

Related to https://github.com/muxinc/media-chrome/discussions/206

**Comment by mikker** [comment]
I'm new to CSS Shadow Parts but I think we'll need `exportparts` too if we want to style when nested inside a `mux-player` element?

**Comment by mikker** [comment]
https://github.com/muxinc/elements/pull/384#issuecomment-1245337163

**Comment by gkatsev** [comment]
It should be available in mux-video. However, we have some concerns about exposing it from mux-player. Started discussion to that point in #380.
