### ISSUE TITLE
Bug: Console error when Thumbnail-token & Storyboard-token are empty

### ISSUE THREAD

**Issue by blairliikala** [muxinc/elements#200]
### Which Mux Elements/Packages has a bug?

Mux Player 0.1.0 beta.8

### Which browser(s) are you using?
Chrome/Edge/FF.

### Which operating system(s) are you using?

macOS

### How are you using Mux Elements?

- script tag

### Describe the bug

When thumbnail and storyboard tokens are left blank, there is an error in the console.
`<mux-player playback-id="{playback_id}" playback-token="" thumbnail-token="" storyboard-token="">`

```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Gt (mux-player:694:11400)
    at Rr.attributeChangedCallback (mux-player:1222:3818)
    at mux-player:1223:1334
    at mux-player:1223:1402
```

## Steps To Reproduce

1. Create a Player element with blank/empty parameters.
2. Look at console.  One for each element.

**Comment by luwes** [comment]
This is fixed 🎉 
https://codesandbox.io/s/mux-player-web-component-leneec?file=/index.html
