### ISSUE TITLE
Docs/Bug: mux-player signed playback creates malformed URL

### ISSUE THREAD

**Issue by ZeusJunior** [muxinc/elements#232]
# Which documentation could use some work?

mux-player

# Is this a discrepancy or an improvement?

discrepancy

## 🖊 Describe what you'd like to see change in the documentation

The mux-player docs on [signed URLs](https://github.com/muxinc/elements/tree/main/packages/mux-player#signed-urls-and-other-playback-query-params) shows you can pass query params, like the token, with the playback ID. But according to the [attributes](https://github.com/muxinc/elements/tree/main/packages/mux-player#attributes) you must seperate the `playback-id` and `playback-token`.
Passing the token with the `playback-id` results in the malformed URL `https://stream.mux.com/playbackid?token=123?redundant_streams=true`
https://github.com/muxinc/elements/blob/3fdf72d0e1322571aa18e8de74649f0dce5ae7b9/packages/mux-player/src/helpers.ts#L29

## 💡 Describe how you think this change will help the documentation
The currently provided documentation on this is incorrect. You can't pass extra query parameters when using signed URLs according to the [mux docs](https://docs.mux.com/guides/video/play-your-videos#add-delivery-redundancy-with-redundant-streams)

Just have to make it clear that you are required to seperate them if using signed URLs (or don't append the `redundant_streams=true` if a token is passed with `playback-id`)

**Comment by gkatsev** [comment]
Thanks for the issue!
Looks like there's some crossed wires in there, we'll take a look!

**Comment by gkatsev** [comment]
Looks like that section of documentation is stale. It used to be possible to pass the token via the playback id, but when we added support for the playback, thumbnail, and storybook tokens, we had to remove support for passing the token via the playback id for consistency.
That section of the docs, unfortunately, was not removed.

PR for this: https://github.com/muxinc/elements/pull/233
