### ISSUE TITLE
Feature: Support vue & Nuxt.js (with SSR)

### ISSUE THREAD

**Issue by cjpillsbury** [muxinc/elements#25]
### Which Mux Elements/Packages would you like a new feature for?

- mux-video
- mux-audio

## 🎥 Describe the feature you'd like to request

Dev's should be able to use any `<mux-element/>` in Vue and Nuxt.js application. That means that a Nuxt.js app with SSR should also build and not throw any errors (even if we cannot do "real" SSR of the components).

## 💻 Describe the use cases the feature will solve

Using these elements in fairly popular/modern web app frameworks (Vue/Nuxt.js)

## ⭐ Describe the solution you'd like to see

Any solution that allows the elements to work in these environments with as little additional work/setup as possible. This may require at least some configuration/setup unless/until we create framework-specific versions of mux-elements. This may only be documentation and/or examples with sufficient smoke testing for now, assuming no code/build changes are required.

For reference:

- Vue - https://v3.vuejs.org/guide/web-components.html#vue-and-web-components
- Nuxt.js - https://github.com/nuxt/nuxt.js/issues/2478#issuecomment-390705197
  - NOTE: While not official documentation, this is the only example I've found that Nuxt.js directly references (See: https://twitter.com/nuxt_js/status/1073228320773468160)

## 🔄 Describe alternatives or workarounds you've considered

N/A

**Comment by pnijhara** [comment]
Hey @cjpillsbury, any progress on this?

**Comment by olivierverwoerd** [comment]
Any progress on this?

**Comment by cjpillsbury** [comment]
@olivierverwoerd / @pnijhara This should work with Nuxt.JS (+ Vue) without any errors but with no SSR. Let me know if it doesn't work for you or if there was something more you were hoping for.

**Comment by troyer** [comment]
On Nuxt I have the following error in the console : 

` mux-player 1.3.0] No stream-type value supplied. Defaulting to `on-demand`. Please provide stream-type as either: `on-demand`, `live`, `ll-live`, `live:dvr`, or `ll-live:dvr``

My code : 

`<template>
    <mux-player
      ref="videoPlayer"
      :autoplay="true"
      :env-key="getMuxEnvKey"
      :playback-id="
        previewMode
          ? video.asset_preview.playback_ids[0].id
          : video.asset.playback_ids[0].id
      "
      :metadata-video-id="video.id"
      :metadata-video-title="video.title"
      :metadata-viewer-user-id="user ? user.uid : null"
      stream-type="on-demand"
    />
</template>
<script>
import '@mux/mux-player'`

The player design/display seems to react to the stream type given though.

**Comment by luwes** [comment]
we added an example of Nuxt.js 3 here https://github.com/muxinc/elements/pull/515 if you're interested, Vite currently has a bundling bug but it works if you use the unbundled versions of the Mux elements.
