### ISSUE TITLE
Add common package for shared code.

### ISSUE THREAD

**Issue by cjpillsbury** [muxinc/elements#27]
There is currently a lot of redundant code across `<mux-audio/>` and `<mux-video/>`. We should have a `common` package that can be shared between the two (and any future elements).

This will require various updates to the build infrastructure and the relationships in the monorepo. Minimally, we should be able to reference the shared code across mux-element packages. Ideally, any changes in the build process would also support hot module replacement so that changes to `common` would automatically trigger a (dev) rebuild and dev server reload.

Furthermore, any code added to `common` should avoid imports of any 3rd party libraries unless we're highly confident that they will be useful for _**ALL**_ mux-elements. This is to avoid pulling unnecessary downstream dependencies when a developer does a package install of a particular element.

**Comment by dylanjha** [comment]
Done in #48
