### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by studio-clinic** [muxinc/elements#274]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux-elements/[element_name]` or `yarn @mux-elements/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
- mux-video

### Which browser(s) are you using?
- Chrome 103.0.5060.53

### Which operating system(s) are you using?
- macOS Monterey 12.2

### How are you using Mux Elements?
- npm packages

### Describe the bug

- Not working with React 18.2
- Not working with --legacy-peer-deps either

## Steps To Reproduce

1. Be on React 18.2
2. npm i @mux/mux-player-react
3.

Link to code example:

## The current behavior

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ms-mel@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from @mux/mux-player-react@0.1.0-canary.0-556dabf
npm ERR! node_modules/@mux/mux-player-react
npm ERR!   @mux/mux-player-react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by studio-clinic** [comment]
@gkatsev Thanks for your help.

I'm still getting the same error with `@mux-elements`. 

It works with `--legacy-peer-deps` but then that won't let me install anything after it.

**Comment by gkatsev** [comment]
@studio-clinic interesting. I guess we need to make sure that our peer dependency properly aligns with the react versions we support so that you won't get multiple versions of react in your builds.

**Comment by cjpillsbury** [comment]
@gkatsev Might want to add different versions of React (back as far as we think is appropriate based on release dates) to our build tests as well.

**Comment by gkatsev** [comment]
When we release the `@mux` the peer deps ranges should be fixed.

**Comment by studio-clinic** [comment]
It's working now, thank you v much!
