### ISSUE TITLE
Bug: No matching version found for @mux/playback-core@0.7.0

### ISSUE THREAD

**Issue by rivajunior** [muxinc/elements#279]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux-elements/[element_name]` or `yarn @mux-elements/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

@mux/mux-video-react

### Which browser(s) are you using?

not applicable 

### Which operating system(s) are you using?

(For example: macOS, Windows, iOS, Android)

WSL Ubuntu 22.04

### How are you using Mux Elements?

(For example: npm package, `<script>` tag)

npm package

### Describe the bug

When trying to install `npm i @mux/mux-video-react`  it got and error `npm ERR! notarget No matching version found for @mux/playback-core@0.7.0.`. 

I think this error occurs because previously the org name used to publish the packages was @mux-elements, but now it is using only @mux. But not every package has its dependencies references updated.

Also. I saw that it was supposed to support react 18 already, But I think it was not published yet.

## Steps To Reproduce

1. `npm i @mux/mux-video-react`

Link to code example:

not applicable 

## The current behavior

![image](https://user-images.githubusercontent.com/11370172/177145033-8506face-d713-4aac-86b2-6664663297b8.png)

## The expected behavior

@mux/mux-video-react gets installed without errors.

**Comment by gkatsev** [comment]
Yeah, we haven't completed the transition to the new scope yet. For now, you should install via the old scope `@mux-elements/element-name`. We hope to have the new scope versions published soon.

**Comment by gkatsev** [comment]
We just published the new scoped packages. Please try re-installing `@mux/mux-player`. Let us know if you run into any other issues.

**Comment by rivajunior** [comment]
@gkatsev I tested with `@mux/mux-video-react` and it worked fine. Thank you!
