### ISSUE TITLE
Bug: mux-player-react fails to integrate with remix.run cloudflare pages

### ISSUE THREAD

**Issue by phpb-com** [muxinc/elements#324]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
- mux-video

### Which browser(s) are you using?

N/A

### Which operating system(s) are you using?

Cloudflare Workers / Miniflare

### How are you using Mux Elements?

npm package

### Describe the bug

Application fails to start when mux-player React component is included. The following errors are produced:

```
[pages:err] TypeError: Global addEventListener() cannot be used in modules. Instead, event handlers should be declared as exports on the root module.
    at addEventListener (/prj/node_modules/@miniflare/core/src/standards/event.ts:273:13)
    at Object.<anonymous> (/prj/functions/[[path]].js:10332:99)
    at t (/prj/functions/[[path]].js:9976:25)
    at Object.<anonymous> (/prj/functions/[[path]].js:10268:23)
    at t (/prj/functions/[[path]].js:9976:25)
    at /prj/functions/[[path]].js:9990:24
    at /prj/functions/[[path]].js:9991:9
    at /prj/functions/[[path]].js:9969:84
    at /prj/functions/[[path]].js:9970:7
    at node_modules/mux-embed/dist/mux.js (/prj/functions/[[path]].js:11716:5)
[pages:inf] Updated `Request.cf` object cache!
```

## Steps To Reproduce

1. Create a sample remix-run application targeting cloudflare workers
2. add @mux/mux-player-react@latest to the project as a run-time dependency 
3. create MuxPlayer element in the app
4. try to run with miniflare or deploy to cloudflare

Link to code example:

```
            <MuxVideo
              style={{ height: '100%', maxWidth: '100%' }}
              streamType="on-demand"
              playbackId="mux.com video id goes here"
              metadata={{
                video_id: 'mux-test-video-0',
                video_title: 'Test video',
                viewer_user_id: 'guest',
              }}
              controls
              autoPlay
            />
```

## The current behavior

App does not start

## The expected behavior

Should start and not complain about `TypeError: Global addEventListener() cannot be used in modules. Instead, event handlers should be declared as exports on the root module.`

**Comment by luwes** [comment]
this seems to have been fixed. let me know if not on your end. thanks for the feedback!

![SCR-20221202-gsv](https://user-images.githubusercontent.com/360826/205357494-901a33d8-8330-4002-b05b-fc58c61571d8.png)
