### ISSUE TITLE
Bug: mux-player ga variable stepping on google analytics

### ISSUE THREAD

**Issue by MrSethT** [muxinc/elements#330]
### Checklist

- [X] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [X] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- mux-video

### Which browser(s) are you using?

- Edge ("Edgeium")

Windows

### How are you using Mux Elements?
`<script>` 

### Describe the bug

I use google analytics that makes a global ga variable to report events.  Since adding mux-player today, ga has been replaced and throws the following error:  Uncaught TypeError: Class constructor ga cannot be invoked without 'new'
ga now evaluates as "class extends gt{static get observedAttributes(){return[...super.observedAttributes,j.MEDIA_CURRENT_TIME,j.MEDIA_DURATION,j.MEDIA_SEEKABLE,"remaining","show-duration"]}connectedCallback(){this.setAttribute("role","progressbar"),this.setAttribute("aria-label",Ye.PLAYBACK_TIME()),this.setAtt...."

in this instance the google analytics snippet is on line 1032 and the mux-player script is called in the head on line 13

## Steps To Reproduce

1.  I'm not sure... sorryy
2.

Link to code example:

## The current behavior
mux-player creates a global object named ga

## The expected behavior
mux-player would not create a global object named ga

**Comment by MrSethT** [comment]
This stopped happening to me on 8/31/2022 when @mux/mux-player@0.1.0-beta.27 released.  I am going to close this.

**Comment by gkatsev** [comment]
Thanks for circling back on this!
