### ISSUE TITLE
Bug: user can seek video with keyboard in live mode

### ISSUE THREAD

**Issue by ramiel** [muxinc/elements#336]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- common

### Which browser(s) are you using?

- Chrome

### Which operating system(s) are you using?

macOS

### How are you using Mux Elements?

npm package

### Describe the bug

When the player is setup in 'live' mode the controls to seek the video are correctly not shown. The user can still seek the video back using the arrow keys

## Steps To Reproduce

1. Set the player in 'live' mode
2. Use the arrow keys to seek the video back

## The expected behavior

In live, seeking the video should be forbidden

**Comment by cjpillsbury** [comment]
Thanks for the callout/catch, @ramiel! We'll be sure to prioritize resolving this ASAP.
