### ISSUE TITLE
Bug: the mux-uploader element doesn't set maxFileSize, while the old uploader did

### ISSUE THREAD

**Issue by jaredsmith** [muxinc/elements#338]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- mux-uploader

### Which browser(s) are you using?

- Chrome

### Which operating system(s) are you using?

MacOS

### How are you using Mux Elements?

using mux-uploader in stream.new

### Describe the bug

`stream.new` currently has two different uploaders -- the `mux-uploader` from this repo for uploading video files, and the older uploader code for videos or screenshares recorded in the browser.  In the older uploader, UpChunk is passed a `maxFileSize` parameter, so that files over 1GB aren't allowed to be uploaded.

`mux-uploader` does not support that configuration option.

## Steps To Reproduce

1.  Attempt to use the `maxFileSize` option with mux-uploader
2. Notice that it fails

Link to code example:

(https://github.com/muxinc/stream.new/blob/main/components/upload-progress-fullpage.tsx#L71)

## The current behavior

`mux-uploader` doesn't use or support the `maxFileSize` option of the UpChunk library

## The expected behavior

Someone using `mux-uploader` should be able to use the `maxFileSize` option.

**Comment by dylanjha** [comment]
Thanks @jaredsmith for reporting

**Comment by dylanjha** [comment]
@davekiss heads up on this one as you're working on the uploader
