### ISSUE TITLE
Module not found: Can't resolve '@mux/mux-player-react/*'

### ISSUE THREAD

**Issue by sharpsteelsoftware1** [muxinc/elements#351]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- mux-player-react

### Which browser(s) are you using?

- Chrome

### Which operating system(s) are you using?

macOS

### How are you using Mux Elements?

yarn add @mux/mux-player
yarn add @mux/mux-player-react

"@mux/mux-player": "^0.1.0-beta.26",
"@mux/mux-player-react": "^0.1.0-beta.26",

### Describe the bug

Importing produces an error: "Module not found: Can't resolve '@mux/mux-player-react/*'"

## Steps To Reproduce

Run yarn add steps
Use MuxPlayer react component

Link to code example:

```
import MuxPlayer from "@mux/mux-player-react/*"

const VideoPlayer = () => {

  return (
    <>
      <MuxPlayer
        stream-type="on-demand"
        playback-id="r4By6336OYm5C8LlXorMZ201K9kJ1nw014KzGEDCDmFaQ"
      />
    </>
  )
}

export { VideoPlayer }

```

## The current behavior
muf-web             | wait  - compiling /video/[slug] (client and server)...
muf-web             | error - ./src/components/widget/VideoPlayer.js:1:0
muf-web             | Module not found: Can't resolve '@mux/mux-player-react/*'
muf-web             | > 1 | import MuxPlayer from "@mux/mux-player-react/*"
muf-web             |   2 | 
muf-web             |   3 | const VideoPlayer = () => {
muf-web             |   4 | 
muf-web             | 
muf-web             | Import trace for requested module:
muf-web             | ./src/feature/video/VideoBySlugPage.tsx
muf-web             | ./src/pages/video/[slug].tsx
muf-web             | 
muf-web             | https://nextjs.org/docs/messages/module-not-found

## The expected behavior
It should just work

**Comment by dylanjha** [comment]
Hi @sharpsteelsoftware1, thanks for the issue

I might be mistaken, but it looks like you might have a trailing slash there, can you change:

```js
import MuxPlayer from "@mux/mux-player-react/*"
```

to 

```
import MuxPlayer from "@mux/mux-player-react"
```

Let me know if that helps. Also, if we have some incorrect documentation that you copy/pasted for that, please let me know so we can fix it.

**Comment by dylanjha** [comment]
@sharpsteelsoftware1 did that fix it?

Also by chance, was that like auto-inserted by VSCode?

**Comment by dylanjha** [comment]
I'm going to go ahead and close this, @sharpsteelsoftware1 please reopen if you're still running into this problem!
