### ISSUE TITLE
Docs: how to access media current time?

### ISSUE THREAD

**Issue by pdrbrnd** [muxinc/elements#369]
# Which documentation could use some work?
In the [Mux Player (beta)](https://docs.mux.com/guides/video/mux-player#events) Events docs it states that we can listen for a "timeupdate" event to track how much of a particular video a user has watched.
The event contains the `mux-player` element and a `timeStamp` int, which is [the number of milliseconds elapsed from the beginning of the time origin until the event was created](https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp).
Is there any way to access data like `media-current-time` or `media-duration` without recursively querying the custom element's shadowRoots?

Still somewhat related to this issue, isn't it possible to access something similar to the [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) so we can access data like `currentTime`, but also trigger a `play()` programmatically? I have absolutely no experience with web-components so this might be an absurd question.

- general mux-elements documentation

# Is this a discrepancy or an improvement?

- improvement

## 🖊 Describe what you'd like to see changed in the documentation

More details on how to access the media's metadata

**Comment by luwes** [comment]
thanks for the feedback @pdrbrnd. That's really easy, almost all properties, methods and events of `HTMLMediaElement` are also available on the `MuxPlayerElement`. Just get the mux-player DOM element and check `muxPlayer.currentTime`.

Hope this helps!

**Comment by pdrbrnd** [comment]
That's perfect :) thanks for the quick reply!

**Comment by austincollinpena** [comment]
What about for a react element? I'm currently using a ref and accessing like `videoRef?.current?.currentTime` but is there a better way?

**Comment by luwes** [comment]
@austincollinpena using React that is the best way I think, you got it right!

**Comment by austincollinpena** [comment]
How do I access the currentTime via react though? I'm not seeing the currentTime value appear consistently.
![image](https://user-images.githubusercontent.com/43731610/210610845-fe6ee248-0744-4284-93e5-9d224826f1da.png)

**Comment by luwes** [comment]
it will not be at the top of those properties list because they're props added by the custom element.
it should be there as a getter scrolling down.

![SCR-20230104-fti](https://user-images.githubusercontent.com/360826/210613431-babc83bd-1f4d-4b49-b233-1bc5baeb697f.png)

**Comment by austincollinpena** [comment]
Awesome, thank you
