### ISSUE TITLE
Question: [ Remove play/stop on click video]

### ISSUE THREAD

**Issue by ProofWoW** [muxinc/elements#379]
Hello,

How i Can remove click event on the video? Now when you press to video element, by default triggering stop/play

Thank you!

**Comment by gkatsev** [comment]
Thanks for the issue! It doesn't seem like there's currently a way to turn off the click to play on the video element.

We can probably export the gestures layer, and then you'll be able to turn it off via CSS (and `::part`)

**Comment by gkatsev** [comment]
In our next release, you'll be able to do something like:
```css
mux-player::part(gesture-layer) {
  display: none;
}
```

**Comment by luis-solano-coda** [comment]
> mux-player::part(gesture-layer) {
  display: none;
}

Is this actually working? I have latest installed and this selector with this style does not reflect any difference. Other selectors are working fine though.

**Comment by luwes** [comment]
@luis-solano-coda does this not work on your end?
https://codesandbox.io/s/mux-player-web-component-gestures-disabled-c5ismo

**Comment by marcelfahle** [comment]
Oh this is excellent, thank you Wesley! Works great over here!
