### ISSUE TITLE
Bug: Pause and seek buttons always showing whilst fullscreen

### ISSUE THREAD

**Issue by WillPoulson** [muxinc/elements#390]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

mux-video
mux-player

### Which browser(s) are you using?

Only tested in Chrome

### Which operating system(s) are you using?

MacOS

### How are you using Mux Elements?

npm package

### Describe the bug

When entering full screen the grey overlay continues to show with the pause and seek buttons. There is no way to make this disappear making the watching experience in fullscreen unusable.

## Steps To Reproduce

1. Fullscreen a mux-player or mux-video video. For example the demo found on https://www.mux.com/player
2. Pause/Seek buttons and grey overlay stay visible no matter how long you wait

Link to code example: https://www.mux.com/player

## The current behavior
When in fullscreen the pause/seek buttons and grey overlay stay visible no matter how long you wait

## The expected behavior
When in full screen the pause/seek buttons and grey overlay should only appear when moving the cursor. Not on hover.

**Comment by WillPoulson** [comment]
To follow on from this, interacting with the controls and then waiting a duration does hide the controls.

The issue only seems to be present when initially opening the fullscreen window.

**Comment by WillPoulson** [comment]
Closing as several colleagues couldn't replicate on Windows and MacOS Chrome. Must be something funky with my machine.

**Comment by gkatsev** [comment]
@WillPoulson When you go fullscreen and click play, do you leave the mouse hovering over controls? Because that probably keeps the controls in focus.
However, we potentially want to auto-hide controls on fullscreen on the next play. Something to think about.

**Comment by WillPoulson** [comment]
@gkatsev The controls were left unhovered, mouse position always left in the transparent grey overlay away from the play buttons. As it's just me in the team experiencing this I think we can ignore it 👍 

Auto-hiding the controls when entering fullscreen sounds like a good idea for the future 😄 

So far everything else is working great for me when implementing this

**Comment by gkatsev** [comment]
@WillPoulson 👍🏻. Did a restart of the browser/device affect this behavior for you at all? Sometimes it helps, still 😆.

Yeah, we'll discuss on how to improve things around this area.
