### ISSUE TITLE
Bug: @mux/mux-video-react autoPlay cannot be changed

### ISSUE THREAD

**Issue by shrugs** [muxinc/elements#396]
### Which Mux Elements/Packages has a bug?

- `@mux/mux-video-react`

### Which browser(s) are you using?

- Firefox

### Which operating system(s) are you using?

macOS

### How are you using Mux Elements?

npm package `@mux/mux-video-react`

### Describe the bug

When setting the `updateAutoplay` function, one must pass a function -> function, since when `useState`'s setter receives a Function, it evaluates it. To store a function in state one must `setState(() -> () -> { ...code... })`

https://github.com/muxinc/elements/blob/b96b98746bbed68d4f82b0ac943c0ce194c1a72e/packages/mux-video-react/src/index.tsx#L67

As it is, react runs that function once, then sets `updateAutoplay` to the return value of that function, which is `undefined`. As such, when the effect runs `updateAutoplay` after changing the autoplay value in props, an invalid function is invoked.

## Steps To Reproduce

1. Render mux video element with autoplay = false
2. render mux video element with autoplay = true
3. see error

**Comment by cjpillsbury** [comment]
@shrugs good catch! Poor `MuxVideo` (react) hasn't gotten enough attention these days. Adding a ticket, but also feel free to issue a PR if you wanted to contribute!

**Comment by shrugs** [comment]
i'll propose this today!
