### ISSUE TITLE
Feature: Automatically add mux asset storyboard/thumbnail track when using playback-id

### ISSUE THREAD

**Issue by cjpillsbury** [muxinc/elements#40]
### Checklist

- [x] Confirmed that there isn't already an existing related [feature request](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).
  - (NOTE: If there is a related feature request, we encourage you to add to the discussion to add additional context or simply to upvote it)

### Which Mux Elements/Packages would you like a new feature for?

- mux-video

## 🎥 Describe the feature you'd like to request

When playing mux videos, we should automatically add the storyboard track, at least by default.

## 💻 Describe the use cases the feature will solve

Easy use/integration with media-chrome UI for showing thumbs with the seek-slider/`<media-time-range/>`.

## ⭐ Describe the solution you'd like to see

If a user provides a `playback-id`, automatically generate a `<track/>` with the appropriate attributes.
Optional: Add an attribute `no-storyboard` or similar, to disable this functionality.

## 🔄 Describe alternatives or workarounds you've considered

Manually add/manage tracks alongside the hls.js management of playlist-sourced tracks.

**Comment by luwes** [comment]
this is done in Mux player 🎉
