### ISSUE TITLE
Feature: Add CSS support for poster image

### ISSUE THREAD

**Issue by matt-sanders** [muxinc/elements#444]
## Context
We would like our videos to cover their container. Ensuring the video fits is easily done by targeting the video and applying the correct `object-fit`:
```
::part(video) {
  object-fit: cover;
}
```

However, doing this means that, at certain sizes, we end up with the poster image displaying on top of the video:
![Screen Shot 2022-10-06 at 8 52 36 AM](https://user-images.githubusercontent.com/7637051/194150351-e670d026-9b2f-4985-9a6c-a9407876f947.png)
The example above is subtle, but notice how the poster image is visible on top of the video behind it. On some videos this is very pronounced.

## Feature request
The `<media-poster-image>` is able to be styled by targeting `::part(poster-layer)` but the underlying `img` element is not and has `object-fit: contain` set. Could we either make that a CSS variable ( e.g. `--poster-image-object-fit` ) or expose it with a part so that we can style it directly.

Alternatively, if there's a better way to tell videos to cover and not contain their parent, that'd solve the issue also.

**Comment by luwes** [comment]
Thanks for the feedback! We added a new CSS var that takes care of the poster image and video `object-fit`.
e.g. `--media-object-fit: cover;`

See an example at 
https://codesandbox.io/s/mux-player-web-component-vertical-fit-cover-d7e1mr?file=/index.html

Hope this helps!

**Comment by matt-sanders** [comment]
Awesome, that works perfectly, thanks!
