### ISSUE TITLE
Bug: Type complaining issues with mux-player 1.0.0

### ISSUE THREAD

**Issue by WillPoulson** [muxinc/elements#446]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

mux-playback , mux-player

### Which browser(s) are you using?

N/A - Compile time issue

### Which operating system(s) are you using?

MacOS

### How are you using Mux Elements?

npm package, in an angular typescript project

## Steps To Reproduce

1. install mux-player
2. Attempt to compile angular project after including mux-player element

Link to code example:

## The current behavior

Getting a compile time error

```
Error: node_modules/@mux/playback-core/dist/types/index.d.ts:5:28 - error TS1005: ',' expected.

5 import { StreamTypes, type ValueOf, type PlaybackCore, type MuxMediaProps, type MuxMediaPropsInternal } from './types';
                             ~~~~~~~


Error: node_modules/@mux/playback-core/dist/types/index.d.ts:5:42 - error TS1005: ',' expected.

5 import { StreamTypes, type ValueOf, type PlaybackCore, type MuxMediaProps, type MuxMediaPropsInternal } from './types';
                                           ~~~~~~~~~~~~


Error: node_modules/@mux/playback-core/dist/types/index.d.ts:5:61 - error TS1005: ',' expected.

5 import { StreamTypes, type ValueOf, type PlaybackCore, type MuxMediaProps, type MuxMediaPropsInternal } from './types';
                                                              ~~~~~~~~~~~~~


Error: node_modules/@mux/playback-core/dist/types/index.d.ts:5:81 - error TS1005: ',' expected.

5 import { StreamTypes, type ValueOf, type PlaybackCore, type MuxMediaProps, type MuxMediaPropsInternal } from './types';
                                                                                  ~~~~~~~~~~~~~~~~~~~~~
```

Apologies for the short bug report. I've attempted to clear down node modules and reinstall however that didn't resolve for me either...

**Comment by luwes** [comment]
thanks for the feedback! it looks like the used bundler doesn't support the inline `type` keyword.

do you happen to know which bundler this Angular project is using? esbuild, rollup, or something else?

**Comment by marcelfahle** [comment]
Interestingly, I had the exact same pop up just now in Next.js 11 and 12, after updating from a sub 0 version of mux player to latest. I'm still investigating.

**Comment by marcelfahle** [comment]
Upgrading typescript from 4.3.x to 4.8.x did the trick over here.

**Comment by dylanjha** [comment]
Going to close this and advise that folks on TS 4.3 upgrade to 4.8, I don't think there are major blockers that would prevent people from doing that upgrade
