### ISSUE TITLE
Bug: mux-player-react throws error when entering fullscreen mode

### ISSUE THREAD

**Issue by BjornFridal** [muxinc/elements#458]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
@mux/mux-player-react

### Which browser(s) are you using?
- Chrome

### Which operating system(s) are you using?
macOS

### How are you using Mux Elements?
npm package @mux/mux-player-react

### Describe the bug
When clicking the fullscreen button or using the keyboard shortcut an error occurs.

## Steps To Reproduce
1. Load video via @mux/mux-player-react
2. Click the fullscreen button or use the keyboard shortcut (f).

Link to code example:
https://codesandbox.io/s/funny-tristan-c0h68i?file=/src/App.js

## The current behavior
The player throws an error when attempting to enter fullscreen mode.

## The expected behavior
The player should open in fullscreen mode without throwing errors.

## Screenshot of error
![image](https://user-images.githubusercontent.com/3288437/195312669-6cd3198a-8ce7-46f4-bf35-13f54f253943.png)

**Comment by luwes** [comment]
@BjornFridal thanks for the feedback! this is related to Codesanbox iframe's not having the permissive policy `allow="fullscreen"` on them. Try opening the demo section with the url in a new window and fullscreen will work as expected. let me know if this would not do the trick!

**Comment by BjornFridal** [comment]
Thanks for the swift response 👍
