### ISSUE TITLE
Bug: mux-player-react stretches the video in fullscreen mode

### ISSUE THREAD

**Issue by BjornFridal** [muxinc/elements#461]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
@mux/mux-player-react

### Which browser(s) are you using?
- Chrome

### Which operating system(s) are you using?
macOS

### How are you using Mux Elements?
npm package @mux/mux-player-react

### Describe the bug
When entering fullscreen mode the video is stretched to fill the entire screen, but without respecting the aspect ratio.

I noticed a PR from a couple of days ago that introduces object-fit styling to the video (#455). Could be related.

## Steps To Reproduce
1. Load video via @mux/mux-player-react
2. Click the fullscreen button or use the keyboard shortcut (f).

## Link to code example:
https://codesandbox.io/s/peaceful-bhabha-y5z3eu?file=/src/App.js

## The current behavior
In fullscreen mode the video is stretched to fill the entire screen, but without respecting the aspect ratio.

## The expected behavior
In fullscreen mode the video should fill the entire screen while keeping the aspect ratio.

### Screenshot when not in fullscreen mode
![image](https://user-images.githubusercontent.com/3288437/195445799-10946de1-2969-46bc-a77b-1463bcaceb53.png)

### Screenshot when in fullscreen mode
![image](https://user-images.githubusercontent.com/3288437/195446357-125ed827-2aaa-416e-ae26-afe021e9e009.png)

**Comment by gkatsev** [comment]
@BjornFridal this should be fixed in 1.1.3 via https://github.com/muxinc/elements/pull/460 🎉

**Comment by BjornFridal** [comment]
@gkatsev I can confirm that, Ed is back to his normal aspect ratio in fullscreen mode in v. 1.1.3! :) 

![image](https://user-images.githubusercontent.com/3288437/195520634-95f17f07-6f7d-4713-ac2c-c9aad19798a4.png)
