### ISSUE TITLE
Feature/fix: Expose mxp-dialog and media-loading-indicator

### ISSUE THREAD

**Issue by richard-grosjean** [muxinc/elements#490]
We want to hide mxp-dialog and media-loading-indicator, and while using JS to dig into the nested shadow tree works, I would much rather have parts assigned and exposed so that they can easily be manipulated with CSS.

In this case Mux is being used for background videos, and both the loading indicator and dialog are interfering with the desired visual experience.

To this end, I have submitted two pull requests: #489 #487 

The dialog element has only been an issue so far if the user is having other issues like a poor internet connection. But as I mentioned above, I would rather have the video fail silently in this case and hiding the mxp-dialog element seemed to be the simplest solution to me.

**Comment by dylanjha** [comment]
Going to close this as a followup to what we discussed on https://github.com/muxinc/elements/pull/489
