### ISSUE TITLE
Programmatically open picture-in-picture PIP mode

### ISSUE THREAD

**Issue by sharpsteelsoftware1** [muxinc/elements#493]
Hi. I am currently using MuxPlayer and noticed that there is a Picture-in-Picture button that when clicked puts the video in a smaller contained window. This is great. I'd like to programmatically put into picture-in-picture mode when they click a button. I have not been able to find PIP captured in documentation.

**Comment by dylanjha** [comment]
@sharpsteelsoftware1 did that work for you? I'm going to go ahead and close this because I tested it out and it worked for me
