### ISSUE TITLE
Bug: MuxPlayer React component resets playback time to 0 after arbitrary setState happens 

### ISSUE THREAD

**Issue by dylanjha** [muxinc/elements#506]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?

- mux-player-react

### Which browser(s) are you using?

- Chrome

### Which operating system(s) are you using?

macOS

### How are you using Mux Elements?

npm packate

### Describe the bug

Calling `setState` in a React component is causing the player to reset back to time `0`

## Steps To Reproduce

See codesandbox: https://codesandbox.io/s/debug-set-state-vz0j3p

1. start playing
1. cick "set some state"
1. player resets back to beginning of the video
1. seems to only happen on the first time clicking "set some state" subsequent clicks on "set some state" do not reset the player back to 0

## The current behavior

Player resets back to 0

## The expected behavior

Player should not reset back to 0, playback should continue uninterrupted

**Comment by raytiley** [comment]
I think I found a work around by simply calling `useEffect` during initial render and setting a throw away state like `mounted`. This will force the player to `0` before the user has had a chance to interact with it, and seems to work ok for my use case.

https://codesandbox.io/s/debug-set-state-forked-oemyii?file=/App.js

**Comment by dylanjha** [comment]
Well that feels a little silly, but a worthy work-around for the time being.

Thanks for sharing, we'll have to dig into this to find a permanent fix
