### ISSUE TITLE
Feature: Decrease mux-video Preload Amount

### ISSUE THREAD

**Issue by luwes** [muxinc/elements#51]
### Checklist

- [x] Confirmed that there isn't already an existing related [feature request](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).
  - (NOTE: If there is a related feature request, we encourage you to add to the discussion to add additional context or simply to upvote it)

### Which Mux Elements/Packages would you like a new feature for?

- mux-video
- mux-audio

## 🎥 Describe the feature you'd like to request

- Initial suggestion is to decrease the amount of video content `mux-video` loads right after the player is initialized.
Currently the default of hls.js is to preload 60MB (explanation is that this is the browser's default behavior). 
I have yet to see other player software that preloads that much content besides hls.js
https://api.playerx.io/render?url=https://stream.mux.com/r4rOE02cc95tbe3I00302nlrHfT023Q3IedFJW029w018KxZA.m3u8

- Preload only when needed, maybe based on viewport, mouse / touch coordinates, etc...

## 💻 Describe the use cases the feature will solve

- Spare the user's bandwidth
- I imagine page load time could be affected by loading this much video right away
- Google Lighthouse penalizes this behavior if the player is loaded on page load

## ⭐ Describe the solution you'd like to see

It might make more sense to load ahead in terms of seconds instead of MB, and it should not be much more than 10s I think.
Currently on my computer the clip above preloads content for a playback time of 1m45s 😳

## 🔄 Describe alternatives or workarounds you've considered

This might not be the right place to change it, either upstream in hls.js code or downstream somewhere, maybe document it clearly...

**Comment by cjpillsbury** [comment]
Let's discuss. We can definitely play around with updating our default hls.js config to use a different value for https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxbuffersize. My high level concern is that this value is a generic value for buffer size and not simply for preload, so it will have broader effects on playback. For now, I'd say we should at least keep the default time-based value @ the hls.js default of 30s, since there are a lot of variables including poor network conditions, seek scenarios, etc. where we wouldn't want to over optimize for more ideal scenarios (in other words, people hate excessive rebuffering).

**Comment by luwes** [comment]
Yes, it does affect the loaded ahead buffer size during the whole session but still it's a very large amount hls.js is loading ahead. Shaka has 10s by default, https://github.com/google/shaka-player/blob/master/lib/util/player_configuration.js#L140
. Vimeo I believe did 2 or 3 segments of 6s but it did not preload video data at all before playback.

This is a plain `<mux-video>` embed, it almost preloads the whole video.
https://api.playerx.io/render?url=https://stream.mux.com/r4rOE02cc95tbe3I00302nlrHfT023Q3IedFJW029w018KxZA.m3u8

**Comment by gkatsev** [comment]
Could be clever and set the maxBufferSize to something small and then when playback begins reset it back to the 60MB. Alternatively, could also use maxBufferLength instead.

**Comment by luwes** [comment]
closed by implementing preload options
