### ISSUE TITLE
Bug:  issue with building when the mux/mux-player-react is installed

### ISSUE THREAD

**Issue by terryli0095** [muxinc/elements#524]
build issue with building after installing mux/mux-player-react @1.5.1
typescript version @4.3.5
node version 18 

Tried to switch to mux-video-react @0.7.2  still the same issue

![Screen Shot 2022-12-16 at 11 41 13 AM](https://user-images.githubusercontent.com/19996922/208176150-2a96f5f1-733b-4867-8c4b-bda218a6f2dd.png)

### Checklist

- [*] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [*] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
mux-video-react @0.7.2 and mux/mux-player-react @1.5.1

### Which browser(s) are you using?
unrelated
### Which operating system(s) are you using?
macOS

### How are you using Mux Elements?
npm package/yarn

### Describe the bug
yarn tsc, or next build  both failing
## Steps To Reproduce
yarn tsc

Link to code example:

## The expected behavior
expect to be able to build

**Comment by gkatsev** [comment]
Seems like these inline type imports may not be available prior to TS 4.5 https://www.typescriptlang.org/docs/handbook/2/modules.html#inline-type-imports

**Comment by gkatsev** [comment]
Though, we do use downlevel-dts, which should [handle this](https://github.com/sandersn/downlevel-dts#type-modifiers-on-importexport-names-45), so, not sure exactly what's wrong here.

**Comment by gkatsev** [comment]
Oh, I see. For whatever reason, it's using the later syntax, i.e. `dist/types/index.d.ts`. It should be using `dist/types-ts3.4/index.d.ts`, based on the config of playback-core:
```json
{
  "types": "dist/types-ts3.4/index.d.ts",
  "typesVersions": {
    ">=4.3.5": {
      "*": [
        "dist/types/index.d.ts"
      ]
    }
  }
}
```

**Comment by gkatsev** [comment]
As @luwes kindly pointed out, it could be that our version range in the `typesVersions` is too permissive, and I just didn't realize that when looking earlier.

@terryli0095 if you are able/get the chance, can you manually modify the package.json locally (`./node_modules/@mux/playback-core/package.json`) to be `">4.5"` in the `typesVersions` and see if some of these errors go away?

**Comment by brycedbjork** [comment]
I can confirm that the build errors go away when the typesVersion is updated to `>4.5`
