### ISSUE TITLE
Bug: No stream-type value supplied warning, when `on-demand` specified 

### ISSUE THREAD

**Issue by stolinski** [muxinc/elements#535]
### Which Mux Elements/Packages has a bug?

mux-player

### Which browser(s) are you using?

Chrome

### Which operating system(s) are you using?

MacOS

### How are you using Mux Elements?

Svelte Kit

### Describe the bug

I'm seeing the warning `[mux-player 1.5.1] No stream-type value supplied. Defaulting to `on-demand`. Please provide stream-type as either: `on-demand`, `live`, `ll-live`, `live:dvr`, or `ll-live:dvr` Read more:` Even thought the attribute exists in my code as `stream-type="on-demand"` as well as the attribute shows up correctly in the DOM.

**Comment by gkatsev** [comment]
We thought that we had this fixed, but it could have to do with the Svelte. We'll have to investigate.

The previous workaround is to make sure that stream-type is set on the element prior to the playback-id. Hopefully, it still works here.

**Comment by dylanjha** [comment]
Hi @stolinski , as @gkatsev mentioned there *used* to be a bug where this showed up based on the order of attributes.

We fixed that [in 1.4](https://docs.mux.com/guides/video/mux-player-releases#140), but maybe in Svelte something weird is going on. Can you just confirm that you're on the latest release?

**Comment by luwes** [comment]
closing for now, let us know if this issue persists.
