### ISSUE TITLE
Bug: Bottom play button removed in small video sizes (but not large or extra-small)

### ISSUE THREAD

**Issue by anton-rob** [muxinc/elements#554]
### Checklist

- [x] Verified whether your issue exists in the latest version Mux Element(s) release: `npm install @mux/[element_name]` or `yarn @mux/[element_name]`.
  - (NOTE: If the issue is not occurring in the latest version, we may not resolve it.)
- [x] Confirmed that this issue hasn't [already been filed](https://github.com/muxinc/elements/issues?q=is%3Aopen+is%3Aissue+label%3Abug).

### Which Mux Elements/Packages has a bug?
mux-player

### Which browser(s) are you using?
- Chrome
- Safari
- Firefox

### Which operating system(s) are you using?
macOS

### How are you using Mux Elements?
npm package, <script> tag

### Describe the bug
The bottom play button gets removed when the video player is around 500px wide. large and extra-small sizes shows the play button. This causes extra problems in situations where we don't want to use the center controls. 

## Steps To Reproduce
1. Embed the video player, with a size around 500px.

Link to code example:
https://jsbin.com/newipeq/2/edit?html,output

![demo](https://user-images.githubusercontent.com/646696/214735929-4f9f567a-621e-494a-94eb-e63deddc056a.png)

## The expected behavior
Always show / enable a way to always show the bottom play button.

**Comment by gkatsev** [comment]
Hi, this has been our expected behavior. We had the play button move to the center only for that player size. However, with your prompt, we decided that it's probably worth to always have the play button in the control bar so, we're going to bring it back as part of #556.

**Comment by dylanjha** [comment]
@anton-rob you should see this fixed in the latest canary tag [`1.6.0-canary.0-38ef225`](https://www.npmjs.com/package/@mux/mux-player/v/1.6.0-canary.0-38ef225)

**Comment by anton-rob** [comment]
Thanks for the quick update guys!  👊
