### ISSUE TITLE
Bug: Problems playing HLS created with FFMPEG from S3 bucket

### ISSUE THREAD

**Issue by chberge** [muxinc/elements#571]
### Which Mux Elements/Packages has a bug?
- mux-player

### Which browser(s) are you using?
- Chrome
- Safari
- Firefox

### Which operating system(s) are you using?
macOS, iOS

### How are you using Mux Elements?
<script>-tag
<script src="https://cdn.jsdelivr.net/npm/@mux/mux-player"></script> 

### Describe the bug
Getting the error below:
Network Error - A network error caused the media download to fail

## Steps To Reproduce

1. Create a HLS playlist with ffmpeg

```
ffmpeg -y -i filename.mp4 \
-preset slow -g 48 -sc_threshold 0 \
-map 0:0 -map 0:1 -map 0:0 -map 0:1 \
-s:v:0 1280x720 -c:v:0 libx264 -b:v:0 1200k  \
-s:v:1 1920x1080 -c:v:1 libx264 -b:v:1 3500k  \
-c:a copy \
-var_stream_map "v:0,a:0 v:1,a:1" \
-master_pl_name master.m3u8 \
-f hls -hls_time 4 -hls_list_size 0 \
-hls_segment_filename v%v/hls%d.ts" \
v%v/prog_index.m3u8
```

file structure after ffmpeg:
master.m3u8
v0/hls0.ts
v0/hls1.ts
v0/prog_index.m3u8
v1/hls0.ts
v1/hls1.ts
v1/prog_index.m3u8

3. Upload all files to s3-bucket with same structure
4. Take the url to master.m3u8 and try it in VLC (plays fine)
5. Take the url to master.m3u8 and use in regular html video 
<video src="link.to.master.m3u8" controls></video> 
It works fine.

Use it in Mux-player, nothing.

<script src="https://cdn.jsdelivr.net/npm/@mux/mux-player"></script> 
<mux-player
src="https://sos-ch-dk-2.exo.io/plaii-recordings/recordings/bf7d6c463375ab47d0a9_3905138e86daba45ffe5_2023-02-06_2044/master.m3u8"
type="application/vnd.apple.mpegurl"
env-key="env-key"
prefer-playback="mse"
stream-type="on-demand"
preload="none"
>
</mux-player>

The master.m3u8 file looks like this:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1495909,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
v0/prog_index.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=4025909,RESOLUTION=1920x1080,CODECS="avc1.640032,mp4a.40.2"
v1/prog_index.m3u8

And the v0/prog_index.m3u8 looks like this:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:5.760000,
hls0.ts
#EXTINF:3.840000,
hls1.ts
#EXTINF:3.840000,
hls2.ts
#EXTINF:3.840000,
hls3.ts
#EXTINF:3.840000,
hls4.ts
#EXTINF:3.840000,
hls5.ts
#EXTINF:3.840000,
hls6.ts
#EXTINF:3.840000,
hls7.ts
#EXTINF:3.840000,
hls8.ts
#EXTINF:3.840000,
hls9.ts

And the v1/prog_index.m3u8 looks like this:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:5.760000,
hls0.ts
#EXTINF:3.840000,
hls1.ts
#EXTINF:3.840000,
hls2.ts
#EXTINF:3.840000,
hls3.ts
#EXTINF:3.840000,
hls4.ts
#EXTINF:3.840000,
hls5.ts
#EXTINF:3.840000,
hls6.ts
#EXTINF:3.840000,
hls7.ts
#EXTINF:3.840000,
hls8.ts
#EXTINF:3.840000,
hls9.ts

## The current behavior
Not playing the HLS

## The expected behavior
Should be playing the HLS

**Comment by cjpillsbury** [comment]
@chberge Just as an FYI, Mux Player does not officially support content that is not provided by [Mux Video](https://docs.mux.com/guides/video). That said, this appears to be a CORS issue. Make sure you configure your static HTTP setup for S3 with appropriate CORS headers. I confirmed locally by using a [CORS Chrome Extension](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf/related?hl=en) to override the server CORS setting to `*` and loading the src you provided. Additionally, the errors in the dev tools will give you clues for when this is a CORS policy issue. e.g. when loading without the extension enabled, you should see something like:
```
Access to XMLHttpRequest at 'https://sos-ch-dk-2.exo.io/plaii-recordings/recordings/bf7d6c463375ab47d0a9_3905138e86daba45ffe5_2023-02-06_2044/master.m3u8?CMCD=cid%3D%22https%3A%2F%2Fsos-ch-dk-2.exo.io%2Fplaii-recordings%2Frecordings%2Fbf7d6c463375ab47d0a9_3905138e86daba45ffe5_2023-02-06_2044%2Fmaster.m3u8%22%2Cmtp%3D500%2Cot%3Dm%2Csf%3Dh%2Csid%3D%2291d034aa-aba2-4b20-9d49-9246ec268882%22%2Csu' from origin 'http://127.0.0.1:8004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by chberge** [comment]
Awesome, thanks! CORS-settings solved it!
