### ISSUE TITLE
Docs: Quality Controls

### ISSUE THREAD

**Issue by ScottAgirs** [muxinc/elements#572]
# Which documentation could use some work?

- mux-video
- general mux-elements documentation
- hls

## 🖊 Describe what you'd like to see a change in the documentation

HLS is great, but it feels a little odd that there is no way to natively select video quality. For example, if the content of the video is quality-critical, IMHO the user should be able to select the quality explicitly.

Currently, I have not been able to find a way how to enable the quality controls neither in `mux-player-react` nor make `plyr` work with Mux source :( This is a major pain point, and I hope that I'm simply missing something. Am I?

**Comment by gkatsev** [comment]
This is definitely not available yet. However, we're working diligently to create such a menu. Unfortunately, we don't have a timeline for that yet, but it's definitely a highly requested feature.

**Comment by aminamos** [comment]
@gkatsev question related to this item: when the quality selector is released in the future, if someone selects a quality level above what their connection can support, wouldn't they have a "worse" viewer experience?

Example: someone wants to lock their resolution at 1080p, their connection can only reliably support 480p, as a result they would experience buffering...right?

**Comment by gkatsev** [comment]
@aminamos yes, theoretically, they could have a worse experience. It would depend on how much can get preloaded ahead of time (often not much with MSE, which is why offline download could be helpful, but that's a whole other 🥫🪱). At the same time, users often know that their internet isn't that good and expect the extra buffering for the higher quality.

**Comment by ScottAgirs** [comment]
If I may, I'd like to add to this - while indeed it may require more pre-buffering/waiting which would result in a worse UX, I would argue in certain cases the trade-off is worth it when the ability to see detail is critically important, I'll spare y'all the list of use-cases that comes to mind. 😃

**Comment by cjpillsbury** [comment]
resolved by #734 (should be coming soon thanks to @luwes's valiant efforts, @ScottAgirs!)
