### ISSUE TITLE
Bug: mux-player-react Black bars when shrinking down viewport size dont show like they do with the regular mux player

### ISSUE THREAD

**Issue by devlukedreamstage** [muxinc/elements#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react

### Which browsers are you using?

Chrome

### Which operating systems are you using?

Windows

### Description

While using the mux react player, when I shrink down the page view height, the ui gets overflowed and the video does not shrink and show black bars. I noticed that in other examples such as the regular mux player as seen here[](https://codesandbox.io/s/8qw5pb?file=/index.html&utm_medium=sandpack) when you scale down the size of the window the ui of the html mux player, black bars show instead of the content being overflowed which is what I want. 

However, I shrink the view port width of the page, the video does scale down.

Gif of my problem: ![lkj](https://user-images.githubusercontent.com/111782608/221300778-cf2177ff-6118-4f80-840d-3ff18f9b34a6.gif)

Gif of what I want to happen: ![lkjkjh](https://user-images.githubusercontent.com/111782608/221301348-64128799-19a7-4aed-9c1f-7c18725f02cb.gif)

### Reduced test case

https://codesandbox.io/s/still-shadow-ypcbdp?file=/src/App.js

### Steps to reproduce

1. Go the codesand box replication
2. Click on the "Open in new window" to open a deployed version of replication
3. Shrink the view height of the page as seen in my gifs.

### Current Behavior

Video does not shrink down and creates overflow causing a lack of vertical responsiveness compared to the 

### Expected Behavior

I noticed that in other examples such as the regular mux player as seen here[](https://codesandbox.io/s/8qw5pb?file=/index.html&utm_medium=sandpack) when you scale down the size of the window the ui of the html mux player, black bars show instead of the content being overflowed which is what I want.

### What version of the package are you using?

1.1.2 (Also tested with 1.8.0)

**Comment by luwes** [comment]
thanks for the feedback and the demo.

I believe this is related to the CSS styles of the wrapper element, not specific to the player.

have a look here https://codesandbox.io/s/objective-frog-czcw1d?file=/src/styles.css

you should be able to position and resize the player as you like with CSS.
closing as it's not related directly to the player code. let us know if it does not seem to work or you find an issue.

**Comment by devlukedreamstage** [comment]
@luwes Is there anyway for the player to keep the full width and height and show black bars instead of  just shrinking? I appreciate the demo.

**Comment by luwes** [comment]
updated https://codesandbox.io/s/objective-frog-czcw1d?file=/src/styles.css

**Comment by devlukedreamstage** [comment]
@luwes Thanks for that! Turns out also updating from 1.1.2 to 1.8.0 helped fix it? Thank you!!
