### ISSUE TITLE
Show a static constant image in MuxPlayer for audio only sources

### ISSUE THREAD

**Issue by ghost** [muxinc/elements#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Description

When I use `<MuxPlayer>` with audio only files, I can use a `poster` prop to display an image. When the user clicks play, the poster image disappears, and the video player goes black. I'd like the ability to show a constant static video image in the player box from an audio only source. 

### Expected Behavior

1. Could there be a setting to use the `poster` prop of `<MuxPlayer>` to display permanently?
or
2. Can the `poster` prop be used as a permanent display when `audio` is `true`?

**Comment by sharpsteelsoftware1** [comment]
> Hey @sharpsteelsoftware1 we don't currently have anything scheduled to directly support this case but we are actively working on [Themes](https://www.media-chrome.org/en/themes) support for Mux Player that would allow folks to build the UI they want. I still think this may be a useful convenience feature to add to our audio only UI ([example here](https://elements-demo-nextjs-mux.vercel.app/MuxPlayer?title=%22This+is+the+title%22&playbackId=%22x00Y6AhtNCs01UIW02FhPY4H6hZHkQLuiLoD1tTMj00zuxE%22&streamType=%22on-demand%22&audio=true&metadata=%7B%22video_id%22%3A%22videoId20%22%2C%22video_title%22%3A%22Title%3A+Audio+Only%22%7D)), so I'll be sure to add it to our back log and run it by our team's designer to see if he has any thoughts.

Thanks cj. This is useful for folks who want to use Mux for video and audio to provide them with a consistent playback experience. Showing a static poster for the audio-only player allows it to be seamlessly used in layouts containing videos as both players are essentially giving the same contents, aspect ratio and size.
