### ISSUE TITLE
Mux Player React stops playing video when tab loses focus in Chrome

### ISSUE THREAD

**Issue by sharpsteelsoftware1** [muxinc/elements#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Chrome

### Which operating systems are you using?

macOS

### Description

Using MuxPlayer, when a video is playing and another tab is focused or the browser is minimized, the video automatically stops playing

### Steps to reproduce

1. Make a MuxPlayer
2.Play a video
3. Change a tab while the video is playing

### Current Behavior

The video stops

### Expected Behavior

The video and sound should keep playing (like YouTube or other video sites)

**Comment by luwes** [comment]
thanks for the feedback. I did a quick test but can't reproduce this on my end. do you have an example online? thanks

I tried it out here https://elements-demo-nextjs.vercel.app/MuxPlayer?title=%22Landscape+VOD+%28White+Background%29%22&playbackId=%22VcmKA6aqzIzlg3MayLJDnbF55kX00mds028Z65QxvBYaA%22&streamType=%22on-demand%22&metadata=%7B%22video_id%22%3A%22videoId1%22%2C%22video_title%22%3A%22Title%3A+Landscape+VOD+%28White+Background%29%22%7D

**Comment by simonlagneaux** [comment]
I'm experiencing the same issue with Safari on MacOs Sonoma. But it works fine on Firefox or Chrome.
