### ISSUE TITLE
Bug: --media-control-padding isn't getting applied as expected

### ISSUE THREAD

**Issue by alexmf91** [muxinc/elements#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Chrome, Safari

### Which operating systems are you using?

macOS

### Description

I'm trying to add more padding on "--media-control-padding" class but is not applying the styles.
On the browser console works fine, but I tried several ways to do it on the code and was not possible to achieve the desired results.

Ideally the way to solve that would be mux-player::part(control-bar) { }.

### Steps to reproduce

1. Add  "--media-control-padding": 30px style on mux player component
2. Check if that overrides default behaviour, if not try next:
3.  Add the following styles mux-player::part(control-bar) { 
    padding: 30px
}

### Current Behavior

Actually the expected behaviour is not overriding the default behaviour of the media control bar.

### Expected Behavior

Adding the media control padding class like this should override the default behaviour.
```    
<MuxPlayer
    style={{
        "--media-control-padding": 30px
    }} 
/>
```
Or in this way:
```
mux-player::part(control-bar) { 
    padding: 30px
}.
```

### What version of the package are you using?

v0.7.7

**Comment by dylanjha** [comment]
HI @alexmf91, thanks for opening.

Mux Player internally sets the Media Chrome variable `--media-control-padding` to different values at different breakpoints in order to ensure the alignment of the controls is as we expect.

This should work for you though, if you target all of the `bottom` elements with the exported CSS part `bottom`

```
mux-player::part(bottom) {
  padding-top: 30px;
  padding-bottom: 30px;
}
```

Give that a try

**Comment by dylanjha** [comment]
Let us know if that helps @alexmf91
