### ISSUE TITLE
I want to autoPlay video using MuxPlayer react

### ISSUE THREAD

**Issue by murtaza-ch** [muxinc/elements#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Description

I want to autoPlay video using MuxPlayer react.

### Expected Behavior

Currently, I'm not able to autoplay video without muting using mux player react. I know it is not recommended to autoplay without muting. but according to my business model, I need to autoplay the video without muting it like youtube playing their video.

I'm looking for a suitable solution for my use case. Please also provide any code snippets if you have any.

Thank you.

**Comment by gkatsev** [comment]
Autoplay nowadays is [pretty tricky](https://www.mux.com/blog/video-autoplay-considered-harmful) and may not be allowed to happen unless muted. Though, it depends on the browser settings for a particular user.
In Mux Player, [we have extended the regular autoplay property](https://docs.mux.com/guides/player/customize-look-and-feel#autoplay) to allow for easier configuration of autoplay. For example, with `autoplay="any"`, it'll try to autoplay unmuted and if the player cannot autoplay, it'll mute the player and try again.

Unfortunately, there is no way to force autoplay with sound.

**Comment by murtaza-ch** [comment]
HI, one more issue I'm facing that is PIP is not only playing on the current video page and it stops playing on other screens. can you please guide me on how to fix that issue?
