### ISSUE TITLE
Bug: same video on the same page not cached

### ISSUE THREAD

**Issue by iceiceart** [muxinc/elements#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react

### Which browsers are you using?

Chrome, Safari

### Which operating systems are you using?

macOS

### Description

Hello!

I'm using the mux-video-react player in my application and have noticed that the URL of the video fragment it fetches keeps changing even if we run two instances of the player with the same video on the same page. The query parameters that change: sid and mtp. Could you tell what they mean and how we can manage them to enable the HTTP cache? Because the browser cache doesn’t work with constantly changing URL.

### Steps to reproduce

1. Insert one player with src to the DOM
2. Insert second player with the same src to the DOM (for example open modal/ popup)
3. See that in new player loading starts from begin

### Current Behavior

No browser cahing

### Expected Behavior

Browser cahing the fragments 

### What version of the package are you using?

0.7.5

**Comment by dylanjha** [comment]
@iceiceart thanks for opening,

those 2 params are part of CMCD (Common Media Client Data), which we tie back into Mux Data for tracking Quality of Experience.

You can disable CMCD with `preferCmcd="none"`. Give that a try and let us know if it helps

**Comment by dylanjha** [comment]
Closing as expected behavior with CMCD a session query param is expected
