### ISSUE TITLE
Bug: Captions jump to top on hover

### ISSUE THREAD

**Issue by nikolagigic** [muxinc/elements#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Chrome, Safari, Firefox

### Which operating systems are you using?

None

### Description

Sometimes when I hover over the player captions jump to the top for a second and then come back.
This is not the default behavior that happens on hover when closed captions get bottom padding.

This can also be seen on Mux Player Docs customisation page: https://docs.mux.com/guides/player/customize-look-and-feel

### Reduced test case

https://docs.mux.com/guides/player/customize-look-and-feel

### Steps to reproduce

1. Play the video with captions
2. Hover over and out a couple of times while captions are playing

### Current Behavior

Captions go all the way to the top as in the top position is set to 0.

### Expected Behavior

Captions get only the bottom padding.

### What version of the package are you using?

v1.3.0

**Comment by gkatsev** [comment]
Interesting, I did see it bounce to the top for a second, though, it isn't supposed to (the comment is out of date):
https://github.com/muxinc/elements/blob/1d79b9e5dec5136a59735b036cbe04495d28814f/packages/mux-player/src/index.ts#L515-L517

**Comment by nikolagigic** [comment]
@gkatsev is there a way to resolve this?

**Comment by gkatsev** [comment]
Not currently. We're investigating alternatives and courses of action.

**Comment by nikolagigic** [comment]
@gkatsev is there a way to set the captions position to be fixed? e.g. `20px` from the bottom of the player?

**Comment by gkatsev** [comment]
@nikolagigic we just merged a change related to this. It's now available in a canary build `@mux/mux-player-react@1.10.0-canary.0-1f236d4` and will be in an official release the next time we publish.

**Comment by gkatsev** [comment]
Fix is out in version 1.10.1.
