### ISSUE TITLE
Bug: Volume prop not setting initial video volume

### ISSUE THREAD

**Issue by spenweb** [muxinc/elements#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react

### Which browsers are you using?

Chrome

### Which operating systems are you using?

macOS

### Description

The `volume` prop does not behave as expected. I expect the `volume` prop to set the initial volume of the video player. It does upon first page load. However, after changing the volume and then refreshing the page, the player volume uses a value cached in localstorage with the key `media-chrome-pref-volume` instead of the explicit volume passed to the `volume` prop.

I would expect there to be a way to disable the Media Chrome volume caching. As a work-around, I set a timeout to change the volume (which is not ideal):
```js
muxPlayerRef.current.volume = 0.2
```

### Reduced test case

https://codesandbox.io/p/sandbox/competent-margulis-xeqofn

### Steps to reproduce

1. Load the `MuxPlayer` in the browser with the `volume` prop set (can use the CodeSandbox link).
2. Change the volume (can slide the volume slider).
3. Refresh the page.
4. Take note of how the volume is now set to a value different that that of the explicitly set `volume` prop.

### Current Behavior

The `volume` prop is being overridden by the value in localstorage with the key `media-chrome-pref-volume`.

### Expected Behavior

The `volume` prop will be used as the initial volume of the MuxPlayer when set.

### What version of the package are you using?

v1.10.0

**Comment by spenweb** [comment]
Would also be great if there was a reliable way to know when the video player is ready so that I can reliably set the volume after the video player is ready. I see that there may have been such functionality at some point but for some unclear reason the `onPlayerReady` prop was removed in this PR: https://github.com/muxinc/elements/pull/393

**Comment by gkatsev** [comment]
I think right now it's by design, but I can see how it can be confusing. The volume prop I guess can read more like a "use this value if the user hasn't requested something else".

We're going to discuss direction here, and we'll circle back once we have a way forward. We may add a flag to turn off this local storage preference stuff.

----

We've had a lot of discussions around player ready things internally and as mentioned here https://github.com/muxinc/elements/pull/393#discussion_r1175362867, we haven't found a compelling enough need for it yet. Hopefully, addressing this volume thing may also reduce one of your needs on a player ready event.

**Comment by spenweb** [comment]
I think having an option to use (or turn off) saving volume to local storage would be very helpful. I also feel that it would be more intuitive that if the volume prop is set that the volume prop has higher precedence over the value in local storage. 

Given the current behavior, it would probably make more sense for the volume prop to be renamed to defaultVolume and add a comment explaining that the defaultVolume prop is only used when set and there is no volume value found in local storage.

Additionally, there could be a new prop called initialVolume that sets the initial volume of the player. The user can later change the volume level.

**Comment by spenweb** [comment]
I'd be happy to help out with implementing this if it is of interest to you.

**Comment by gkatsev** [comment]
Hey, sorry for the wait. We just released a new attribute called no-volume-pref that disables this localStorage behavior in mux-player 1.11.

The issue with renaming attributes is that if we remove the old attribute it'll be a breaking change, and we're not ready to do a major version update of mux-player just yet. However, you are correct that there's probably better naming for the attributes or at least the documentation for it should be improved.

**Comment by spenweb** [comment]
Looked over the changes in #686 and just updated to v1.11.0 and it seems to work!
