### ISSUE TITLE
Bug:  ReferenceError: i is not defined

### ISSUE THREAD

**Issue by eddiesiegel** [muxinc/elements#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player, mux-player-react

### Which browsers are you using?

Chrome, Firefox, Edge ("Edgeium")

### Which operating systems are you using?

Other (add details below)

### Description

We recently switched over to the React Mux Player (@mux/mux-player-react 1.10.1). Ever since we started using it, we've been seeing errors in Sentry for a subset of our users that look like this:

ReferenceError: i is not defined

The errors have no stack trace so it's hard for me to track down. As a clue, it seems to happen right after a GET request like this:

https://chunk-gcp-us-east4-vop1.fastly.mux.com/v1/chunk/yv02gDneyboLxusAyAbulcRXJrl00tWiNx9wh3Ccnw58PHTtB1yTqCKSiOfsM143hK01ycp02801HlFc6XjbGHD4mSxI02eQVznv1wOfb4TigLxd8/0.ts?skid=default&signature=NjQ2M2QyYjBfYTY4NjA4ODA2NDVlOWFkY2RmM2FhY2ZhYWM4YWVjZWJhOGVhYTk0YzRlODVlYjU0ZDZiYmZmZjhkNDJiZWFiNA==&zone=0&CMCD=br%3D2516%2Ccid%3D4419%2Cd%3D5000%2Cmtp%3D500%2Cot%3Dav%2Csf%3Dh%2Csid%3D%22e6e87cc3-b0eb-4638-8fcc-edebbce99885%22%2Csu%2Ctb%3D4755

And it seems to involve a URL like this: `blob:https://ourdomain.co/5e8ec423-d265-4e83-996d-8d295cb557fc at line 1:371986`

I have attached a screenshot from Sentry in case there is other debug info in there that you find useful.

![Sentry](https://github.com/muxinc/elements/assets/165380/bfeeee3c-255b-4077-adfa-1f84a20d41b1)

### Steps to reproduce

Intermittent and i've had trouble reproducing it. We're seeing it happen w/multiple end-users but haven't been able to replicate ourselves

### Current Behavior

See description

### Expected Behavior

See description

### Errors

ReferenceError: i is not defined

### What version of the package are you using?

@mux/mux-player-react 1.10.1

**Comment by kartikcho** [comment]
Hi @eddiesiegel, I'm facing the exact same issue and can't pin down the cause. 
Were you able to find a fix for it?

**Comment by dylanjha** [comment]
Hmmm that is odd.

For some context: `blob:...` in the video src is expected, that's how [Media Source Extensions](https://www.w3.org/TR/media-source-2/) work.

The fact that there's no stack trace is going to make this quite difficult to debug.

Can you find the Mux Data view in your Mux Data dashboard that corresponds to this error? If you're passing in the user ID as metadata you should be able to use that as a filter to trace it back

**Comment by eddiesiegel** [comment]
Yep I was able to find it. Nothing jumps out at me (no errors, etc.), but here are some screenshots. Please let me know if there is any other info I can share to help you investigate.
<img width="1302" alt="Screenshot 2023-06-27 at 2 15 29 PM" src="https://github.com/muxinc/elements/assets/165380/e11f46ce-37f9-443e-b443-df67f87654d2">
<img width="1302" alt="Screenshot 2023-06-27 at 2 15 43 PM" src="https://github.com/muxinc/elements/assets/165380/5b7b4a9b-0d45-4775-9ddf-2ad4af9f7395">

**Comment by cjpillsbury** [comment]
Hey @eddiesiegel and @kartikcho - I'm actually investigating this right now. It's looking like the issue is pretty deep in the weeds of layered builds + how hls.js generates its web worker-based transmuxer (https://github.com/video-dev/hls.js/blob/master/src/demux/inject-worker.ts#L15-L31). If you all don't mind, could you share any build tools (including versions) and/or app frameworks (including versions) that you are using when you see this error?

**Comment by eddiesiegel** [comment]
Not sure what's relevant so I dumped some of my config files into ChatGPT and it produced this summary:

**Build Tools and Versions:**
- **Babel**: Not explicitly listed, but used within the project (Inferred from Babel plugins and presets)
- **Webpack**: `4.46.0`
- **Webpack-cli**: `3.3.12`
- **Fork-ts-checker-webpack-plugin**: `6.3.3`
- **Sentry Webpack plugin**: `1.20.0`
- **Webpack-dev-server**: `4.2.1` (devDependency)
- **Rails webpacker**: `5.4.3`

**App Frameworks and Versions:**
- **React**: `18.0.0`
- **React-dom**: `18.0.0`
- **Mux-player-react**: `1.11.1`
- **React-bootstrap**: `2.0.0-beta.4`
- **Rails UJS**: `6.0.0`

**Typescript Version:**
- **Typescript**: `4.2.4`

**Key Babel Configurations:**
- **Presets used**: `@babel/preset-env`, `@babel/preset-react`, `@babel/preset-typescript`
- **UseBuiltIns**: `entry` for `@babel/preset-env` and `true` for `@babel/preset-react`
- **Modules**: `commonjs` if testing else `false` for `@babel/preset-env`
- **Corejs**: `3.30` for `@babel/preset-env` and `false` for `@babel/plugin-transform-runtime`

**Key Typescript Configurations:**
- **Target**: `es5`
- **Module**: `es6`
- **ModuleResolution**: `node`
- **JSX**: `react`

**Webpack Module Rules:**
- **.mjs file handling**: Explicitly configuring Webpack to treat '.mjs' files as ECMAScript modules by setting the 'type' to 'javascript/auto'. This is specifically for the 'node_modules/@mux/mux-player-react' directory, which includes '.mjs' files.

**Webpack Resolve Configurations:**
- **extensions**: '.mjs' files are added in the resolved extensions to ensure they are properly imported.

**Babel Loader Exclusion:**
- **node_modules exclusion**: 'mux-player-react' is added to Babel loader exclusion list. This prevents Babel from transpiling certain node_modules packages that were causing console errors when playing videos.

**Webpack Optimization:**
- **SplitChunks**: Enabled to split the code into separate chunks, which helps improve the loading time of the app.

**Comment by cjpillsbury** [comment]
This is great, thanks @eddiesiegel. I'll be sure to keep you posted on any updates from my end.

**Comment by dylanjha** [comment]
@eddiesiegel I think we saw this with another customer and it might have been solved with `v1.11.4` when we changed how Hls.js is bundled. Can you upgrade and see if you're still experiencing the issue?

**Comment by kartikcho** [comment]
@dylanjha @cjpillsbury I can confirm upgrading to `1.11.4` fixed it. Thank you!
