### ISSUE TITLE
Bug: Mux Player won't exit fullscreen (Android)

### ISSUE THREAD

**Issue by mmvsk** [muxinc/elements#692]
### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player and [media-chrome](https://github.com/muxinc/media-chrome)

### Which browsers and OS are you using?

All browsers for Android (because on iOS the native controls are used).

### Description

On Android, if you switch the video to fullscreen mode, then change the orientation of the device, the "exit fullscreen" button won't work. The only way to exit is using the back button.

If the orientation is restored to the original one, it doesn't work either: a single change of orientation inactivates the button.

The only way to keep the button working is to never change the orientation when in fullscreen.

It's the same on all browsers on Android (or any mobile browser without native controls, like iOS),: Chrome, Firefox and Edge. By the way, with Edge, in portrait orientation, there is no controls bar (it only appears when in landscape orientation).

The underlying problem is the `media-fullscreen-button` is re-created when the window is resized past a media query breakpoint, and the new one is missing the `media-is-fullscreen attribute`.

### Reduced test case

https://docs.mux.com/guides/player/play-your-assets

### Steps to reproduce

1. Go to [any page containing a Mux Player](https://docs.mux.com/guides/player/play-your-assets) with an Android phone
2. Press the "enter fullscreen" button on the controls bar of the Mux Player
3. When in fullscreen, change at least once the orientation of the device
4. Try pressing the "exit fullscreen" button: nothing happens

### What version of the package are you using?

1.11.0

**Comment by luwes** [comment]
Fixed in https://github.com/muxinc/media-chrome/issues/627
