### ISSUE TITLE
Bug: Deprecated API warning in Lighthouse

### ISSUE THREAD

**Issue by localghost8000** [muxinc/elements#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player

### Which browsers are you using?

Chrome

### Which operating systems are you using?

macOS

### Description

Chrome Lighthouse reports two deprecated API's.

```
HTMLVideoElement.webkitSupportsFullscreen is deprecated. Please use
Document. fullscreenEnabled instead.

```
```
HTMLVideoElement.webkitDisplayingFullscreen is deprecated. Please use
Document. fullscreenElement instead.
```

### Steps to reproduce

1. Using `@mux/mux-player`, `@mux/mux-player/themes/minimal`, create a video instance like so

```
<mux-player
  preload="auto"
  id="heroBackgroundVideo"
  class="background-video"
  poster="https://image.mux.com/{{ playback_id }}/thumbnail.webp?fit_mode=preserve&time=0"
  stream-type="on-demand"
  playback-id="{{ playback_id }}"
  autoplay="muted"
  loop
  thumbnail-time="0"
></mux-player>
```
2. Open Chrome and run a light house report

### Current Behavior

Results in a Best Practices warning regarding deprecated APIs.

```
HTMLVideoElement.webkitSupportsFullscreen is deprecated. Please use
Document. fullscreenEnabled instead.

```
```
HTMLVideoElement.webkitDisplayingFullscreen is deprecated. Please use
Document. fullscreenElement instead.
```

<img width="754" alt="Screenshot 2023-07-06 at 6 33 24 PM" src="https://github.com/muxinc/elements/assets/2650558/d42a86f7-cc4c-48c4-8d42-5efcd98470ba">

### Expected Behavior

No deprecation warning.

### What version of the package are you using?

1.11.3

**Comment by cjpillsbury** [comment]
Hey @localghost8000
Unfortunately we still need to rely on these properties for cross browser compatibility, particularly for Safari on iOS. See:
- https://caniuse.com/mdn-api_document_fullscreenelement
- https://caniuse.com/mdn-api_document_fullscreenenabled

**Comment by dumle11** [comment]
Is there a way to disable this deprecated API use, if we don't allow for fullscreen/don't show controls?
