### ISSUE TITLE
Bug: react-mux-player and react-mux-video do not play when on mobile

### ISSUE THREAD

**Issue by KrustyC** [muxinc/elements#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react, mux-player-react

### Which browsers are you using?

Chrome, Safari on iOS, Other (add details below)

### Which operating systems are you using?

macOS

### Description

After the latest fix on mux-player-react I wanted to give it a go so switched back the usage of the HTML video tag to use mux-player-react. Everything seemed fine, but once I deployed it to production I noticed that, while it worked on my Mac, it did not work on the iPhone, where the player loads, but the video never starts.

I wanted to also test this with mux-video-react (which I believe would work for my use case, as I am only playing a background video), but that had the same exact issue. 
If it can help, here you can see how I have implemented in both scenarios:
- [mux-video-react](https://github.com/KrustyC/thescrapbookers.blog/blob/main/src/components/home/Video.tsx)
- [mux-player-react](https://github.com/KrustyC/thescrapbookers.blog/blob/main/src/components/home/VideoPlayer.tsx)

I tested this this on both Chrome and Safari from an iPhone 14 Pro.

If you need anything else from me please let me know, and I'd be happy to help where I can

### Reduced test case

https://thescrapbookers.blog

### Steps to reproduce

1. Navigate to https://thescrapbookers.blog on a mobile device (I could only test this on the iPhone 14 Pro)
2. Scroll down to the video

### Current Behavior

The player loads, but the video does not play

### Expected Behavior

I would expect the video to play. If you try to do this on a laptop it works just fine

### What version of the package are you using?

1.11.4 (mux-player-react), 0.7.15 (mux-video-react)

**Comment by KrustyC** [comment]
for some reason this now has just started working, even though I made no change to it 🤔  I will close the issue though

**Comment by vanceingalls** [comment]
the video doesn't work on the link you posted, it just shows a black box. im having trouble with video on mobile as well

**Comment by KrustyC** [comment]
that's exactly the problem to be fair, sometimes it works and sometimes it doesn't

**Comment by vanceingalls** [comment]
so actually, i made a mistake and noticed the issue is different between iOS simulator and an actual device. on your page in the simulator it shows a black box, whereas on an actual device, i see the first frame of the video but it doesn't autoplay.

**Comment by MarsHeer** [comment]
Did you guys find anything new related to this? I'm getting "Source not supported" or "Failed to decode media" errors very consistently, only on mobile.
