### ISSUE TITLE
Bug: Safari video controller style bug

### ISSUE THREAD

**Issue by jackguoAtJogg** [muxinc/elements#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Safari

### Which operating systems are you using?

macOS

### Description

There's a weird bug where I have a `Skeleton` component that breaks mux video player style. When I hover over to the video, the video controller would flash in/out and it only happens in safari.

https://codesandbox.io/s/musing-cdn-6lhhrj?file=/src/App.js:0-18340

### Reduced test case

https://codesandbox.io/s/musing-cdn-6lhhrj?file=/src/App.js:0-18340

### Steps to reproduce

1. Having a Skeleton component

### Current Behavior

The video control become unusable

### Expected Behavior

Works as expected

**Comment by cjpillsbury** [comment]
hey @jackguoAtJogg thanks for filing! This appears to be a bug that was recently introduced in Safari/WebKit. Ideally we can get Safari/WebKit to resolve the core bug. In the interim, would you mind trying this workaround to force an appropriate z-index to see if it sufficiently resolves your issue?

https://codesandbox.io/s/keen-williams-xqp8z6?file=/src/styles.css

Also, would you mind updating your issue description from

> Which Mux Elements/Packages does this apply to? Select all that apply
mux-video-react

to

Which Mux Elements/Packages does this apply to? Select all that apply
mux-player-react

?

**Comment by jackguoAtJogg** [comment]
@cjpillsbury Hi I have tried to use `z-index: 99999` to fix but doesn't seem to be working on safari.
https://codesandbox.io/s/gallant-tu-srzsk7?file=/src/styles.css

I'm happy to update my description but I'm not quite sure what should I update to.

**Comment by cjpillsbury** [comment]
@jackguoAtJogg I'm sorry it looks like we aren't exporting the controller as a `part` yet! I've tested locally with this added and it should resolve your issue. I'll be issuing a PR ASAP to get it added.

Also, re:
> I'm happy to update my description but I'm not quite sure what should I update to.

No worries I went ahead and edited it myself. All I was suggesting is you update to mention this is about `mux-player-react`, since that's the package/component you're using in your project.

**Comment by jackguoAtJogg** [comment]
@cjpillsbury Awesome! Thank you for looking into it!

**Comment by luwes** [comment]
related issue https://github.com/muxinc/elements/issues/644

@jackguoAtJogg seems removing the Skeleton components fixes the issue. Are you sure that's valid CSS? 
It might be fixable just by changing the CSS a little bit.

https://codesandbox.io/s/happy-pasteur-drl9lw?file=/src/App.js

**Comment by cjpillsbury** [comment]
@jackguoAtJogg fyi we just cut a canary release ([1.11.4-canary.0-bb4886c](https://www.npmjs.com/package/@mux/mux-player-react/v/1.11.4-canary.0-bb4886c)) that should now allow you to try my workaround. Here's a fork of your example targeting the canary version and with the part selector (ended up calling it `controller`, not `media-controller`) with it applied and it _**seems**_ to sidestep the browser bug (🤞):
https://codesandbox.io/s/funny-allen-w6xg8y?file=/src/styles.css

Let us know if that helps! We should be cutting an official release sometime early next week that would include these changes.

**Comment by jackguoAtJogg** [comment]
@cjpillsbury I can confirm that is fixed on canary release ([1.11.4-canary.0-bb4886c](https://www.npmjs.com/package/@mux/mux-player-react/v/1.11.4-canary.0-bb4886c))! Thank you really appreciated your help.

**Comment by cjpillsbury** [comment]
@jackguoAtJogg just an fyi the changes are now in our latest official release. Closing this issue but we'll be monitoring WebKit for any fixes here at the browser level. Glad there was at least some workaround for the browser bug!

**Comment by jackguoAtJogg** [comment]
@cjpillsbury This issue is happening again with version `2.2.0`, you can see it by open this sandbox on safari. 

https://codesandbox.io/s/silent-surf-4dlmdd
