### ISSUE TITLE
Bug: `--media-preview-time-margin` can't be customized 

### ISSUE THREAD

**Issue by theazgra** [muxinc/elements#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player

### Which browsers are you using?

Edge ("Edgeium")

### Which operating systems are you using?

Windows

### Description

I need to push preview box up from timeline, `--media-preview-time-margin` would be the correct solution to my problem, but I can't set that CSS variable to be used. Because the shadow-root contains more specific selector, which overrides the CSS variable.

This bug is created as a followup to support ticket #2028837

### Steps to reproduce

1. Add CSS variable to mux player
![image](https://github.com/muxinc/elements/assets/18343952/72b288f7-dba6-466f-9748-d22080623bfd)
2. Hover on timeline to display preview box
3. Preview box is in the same position, no margin is added
![image](https://github.com/muxinc/elements/assets/18343952/e8a7e574-5496-4ecc-a897-edb3f83b74ca)
![image](https://github.com/muxinc/elements/assets/18343952/5f2f9393-460e-495d-98db-c9adf1206fd9)

### Current Behavior

`--media-preview-time-margin` CSS variable can't be changed.

### Expected Behavior

`--media-preview-time-margin` can be set and will be used in the player.

### What version of the package are you using?

latest

**Comment by dylanjha** [comment]
Thanks @theazgra for opening.

@luwes @cjpillsbury I wonder if we might want to expose a CSS part for this?

**Comment by theazgra** [comment]
> Thanks @theazgra for opening.
> 
> @luwes @cjpillsbury I wonder if we might want to expose a CSS part for this?

That would actually be a really good solution and at first I tried to use part, but then noticed that it is not exported.

**Comment by cjpillsbury** [comment]
@theazgra checking out our options now. Will keep you posted.

**Comment by cjpillsbury** [comment]
ok @theazgra luckily our theme-based css variable overrides in this case are defined at the host level. Why does that mean you're lucky? You can already use our pre-existing parts to override that default (simply based on CSS precedence).

Here's a very simple example with an exaggerated value to demonstrate where we target the part that matches "time range" (aka the `media-time-range` used under the hood):
https://codesandbox.io/s/frosty-stitch-59lh4q?file=/index.html

Let me know if that works for you!

**Comment by theazgra** [comment]
@cjpillsbury yea, that works! Thanks a lot. We can close this issue I guess?
