### ISSUE TITLE
Feature Request: export bottom `media-control-bar` part to use custom styles with video controls

### ISSUE THREAD

**Issue by gretchenfitze** [muxinc/elements#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player, mux-player-react

### Description

Hello, we use `mux-player-react` with the default (calssic) theme. We like the theme, but wanted to move the controls a bit bottom, not to overflow the video, and prevent the controls auto-hide when the video is playing. I found no way to style the bottom `media-control-bar` element itself, I can add styles only to the underlying elements with `::part(bottom)`. Would be nice if `media-control-bar` has its own `part` name exported.

### Expected Behavior

It is possible to style the bottom `media-control-bar` with `::part` selector

**Comment by cjpillsbury** [comment]
@gretchenfitze thanks for the feedback! I think this is a great idea. I'll discuss with the team, but, unless something comes up, I think we should be able to add this and get a release out by next week at the latest.

**Comment by cjpillsbury** [comment]
Also, just to call out, we do have some sizing assumptions in relation to the media element and underlying media controller from media chrome. If you end up fighting against some of those assumptions with your bigger picture goals, you may want to just copy our theme and refactor the underly templated DOM structure itself. We'd be happy to help provide guidance on that if that ends up being the case.
