### ISSUE TITLE
t is not defined

### ISSUE THREAD

**Issue by Meghal6217** [muxinc/elements#796]
Getting `t is not defined error` in sentry and after checking got to know that point of origin is the packaged used which is `@mux/mux-video-react`. Please check below screenshot for reference!

![image](https://github.com/muxinc/elements/assets/28785519/ab635467-6245-4928-9f73-2b3740a1c1df)

Steps of error:
1. When mux player is loaded
2. Sentry handles the mentioned error
3. Error is logged on the sentry with additional details

**Comment by daytime-em** [comment]
Thank you for your report.

Sorry you're seeing errors popping up. We will investigate.

Thanks again!!

**Comment by cjpillsbury** [comment]
@Meghal6217 just to make sure, are you using the latest version of mux-video-react? We had some issues recently that at least resembled this that may have been resolved in a recent release.

**Comment by Meghal6217** [comment]
Thanks @cjpillsbury for the info as the error is not been logged till now after updating mux-video-react to the latest version!
