### ISSUE TITLE
Bug: Cant Skip Ahead by dragging and dropping

### ISSUE THREAD

**Issue by JordanKatz** [muxinc/elements#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player

### Which browsers are you using?

Safari

### Which operating systems are you using?

macOS

### Description

Adam Jaggard had a look into this and can re-create the issue we are seeing. Clicking to skip ahead on the progress bar works fine, but dragging and letting go seems to have an issue with initiating the skip.

https://github.com/muxinc/elements/assets/2091443/cd2671de-2801-44b1-9eb4-fd9cee3da9c9

### Reduced test case

https://mystik.bushidoco.de/media/geson-june-6-2023

### Steps to reproduce

1. On Mobile Click https://mystik.bushidoco.de/media/geson-june-6-2023
2. Clicking to skip ahead on the progress bar works fine
3. dragging and letting go creates issue with initiating the skip

### Current Behavior

cant skip ahead by dragging and dropping

### Expected Behavior

drag and drop to any point in the media to skip ahead

### Errors

see video

### What version of the package are you using?

v2.0.1

**Comment by luwes** [comment]
thanks for reporting! 
we are working on a improving this. related PR https://github.com/muxinc/media-chrome/pull/704

**Comment by hivokas** [comment]
Experiencing a similar issue. Works fine on desktop, but same behavior on mobile Safari.

**Comment by luwes** [comment]
yep, @AdamJaggard released this yesterday 🎉
