### ISSUE TITLE
Bug: v2.2.0 broke playbackRates customization

### ISSUE THREAD

**Issue by kentcdodds** [muxinc/elements#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Chrome

### Which operating systems are you using?

macOS

### Description

I'm getting the default playback rates:

<img width="257" alt="image" src="https://github.com/muxinc/elements/assets/1500684/8aa3a339-e40a-47df-b99b-6e69c8cf876d">

Despite my `playbackRates` being set to `playbackRates={[0.5, 1, 1.5]}`

### Reduced test case

https://codesandbox.io/s/mux-player-react-forked-v5g44m?file=/App.js

### Steps to reproduce

1. set `playbackRates` to anything custom

### Current Behavior

The playbackRates prop is ignored and the default is always used

### Expected Behavior

The playbackRates should be used.

### Errors

None.

### What version of the package are you using?

v2.2.0

**Comment by kentcdodds** [comment]
I've confirmed that this is working as expected in v2.1.0: https://codesandbox.io/s/mux-player-react-forked-pmq2nc?file=/package.json:79-112

**Comment by luwes** [comment]
this should be fixed in https://www.npmjs.com/package/@mux/mux-player-react/v/2.2.0-canary.0-799d7a5

and will be included in the next latest release. cheers!

**Comment by kentcdodds** [comment]
Thanks!
