### ISSUE TITLE
Bug: `disablePictureInPicture` prop not allowed

### ISSUE THREAD

**Issue by peduarte** [muxinc/elements#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react

### Which browsers are you using?

Chrome, Safari

### Which operating systems are you using?

None

### Description

Hey team 👋 

Just a little one, but I'm seeing a TypeScript error when using the [`disablePictureInPicture`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/disablePictureInPicture) prop

It works as expected, so the error is only at the typing level. 

I've worked around it for now with this dirty little hack, just to silence the error:

```tsx
 <MuxPlayer {...{ disablePictureInPicture: true }} />
```

Thanks!

### Steps to reproduce

1. `import MuxPlayer from "@mux/mux-player-react";`
2. Render `<MuxPlayer />`
3. Add the `disablePictureInPicture` prop

### Current Behavior

<img width="657" alt="image" src="https://github.com/muxinc/elements/assets/372831/95dc9c3c-64d0-4b97-864c-57175c53a231">

### Expected Behavior

No TS errors

### What version of the package are you using?

2.2.0

**Comment by heff** [comment]
Thanks for the report! Can confirm this happens for me. I submitted [a PR](https://github.com/muxinc/elements/pull/835) that might fix this. Waiting on a review from someone who knows more.
