### ISSUE TITLE
Bug: Blob URL src logs error in MuxPlayer

### ISSUE THREAD

**Issue by vthommeret** [muxinc/elements#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Which browsers are you using?

Safari

### Which operating systems are you using?

macOS

### Description

When using a blob object URL as the source for MuxPlayer (e.g. the recorded data from a camera) this error appears:

`Media type  is an unrecognized or unsupported type for src blob`

It looks like it's coming from here: https://github.com/muxinc/elements/blob/b0409a4ec77c90eaa853c5083e5567b5ea05fbb0/packages/playback-core/src/index.ts#L123

It still works, but just it just seems like it's not expecting a blob object URl.

### Steps to reproduce

Create an object URL from blobs, e.g.

```js
const blob = new Blob(blobs, { type: mimeType })
const objUrl = URL.createObjectURL(blob)
```

Set it as the src of a MuxPlayer, e.g.

```jsx
<MuxPlayer src={objectUrl} />
```

### Current Behavior

`Media type  is an unrecognized or unsupported type for src blob` error appears in console.

### Expected Behavior

No error to appear.

### Errors

`Media type  is an unrecognized or unsupported type for src blob`

### What version of the package are you using?

2.3.1

**Comment by luwes** [comment]
thanks for reaching out, this is expected behavior because we don't officially support the `src` attribute or custom not Mux source URLs in the Mux player. the player will always log an error if the source doesn't look like a Mux source URL I believe.

feel free to use the player with a custom source but we're probably not going to remove the console error. 
hope this helps

**Comment by tauqeer-trailfive** [comment]
Hi @vthommeret,did you find any way to make this error hide or stop?
