### ISSUE TITLE
Bug: React player causes horizontal overflow after video starts

### ISSUE THREAD

**Issue by spenweb** [muxinc/elements#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react

### Which browsers are you using?

Chrome, Safari, Safari on iOS

### Which operating systems are you using?

iOS

### Description

The video player causes unnecessary horizontal overflow after playing the video. As a workaround, I add `overflow: hidden` to the player and the issue goes away.

https://github.com/muxinc/elements/assets/46385475/e17fd9dd-8fec-49fb-a155-d4f960bebba1

The test case comes straight from the documentation: https://docs.mux.com/guides/mux-player-web#example-react-implementation
Here is a copy of the Code Sandbox just in case the original from the documentation is removed: https://codesandbox.io/p/sandbox/awesome-fast-89pwqp

### Reduced test case

https://codesandbox.io/p/sandbox/pedantic-firefly-tgwf2x?file=%2FApp.js

### Steps to reproduce

1. Press play
2. Scroll to the right
3. Notice horizontal scroll
4. Question my own understanding of CSS 🙃

### Current Behavior

The video player causes unnecessary horizontal overflow after playing the video.

### Expected Behavior

There should be no horizontal overflow.

### What version of the package are you using?

v2.3.2

**Comment by daniel-schranz** [comment]
Hej @luwes thank you for having a look at the bug 🙌 I wonder if this was fixed since the bug with horizontal scrollbar is still a bit of a problem in our application. Thanks!

**Comment by luwes** [comment]
thanks for reminding! I repro'd again with the new player v3. it's caused by the unpositioned tooltips.

<img width="1799" alt="SCR-20240927-hlag" src="https://github.com/user-attachments/assets/b8f33321-0210-4dfb-89e8-2a1c415ce4ed">

**Comment by daniel-schranz** [comment]
Lovely, thank you! 🙌
