### ISSUE TITLE
Bug: `mux-uploader-retry` not shown on upload error + retry not reseting `mux-uploader-progress`

### ISSUE THREAD

**Issue by theazgra** [muxinc/elements#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-uploader

### Which browsers are you using?

Edge ("Edgeium")

### Which operating systems are you using?

Windows

### Description

I am reporting two bugs in one issue.

### Reduced test case

https://gist.github.com/theazgra/2c88938a3198540b6e6ecb9324e47d3c

### Steps to reproduce

1. Provide invalid endpoint url to trigger upload-error
2. Try to upload video/audio
3. Upload fails

### Current Behavior

Upload fails. Correct status message (error message) is shown. But retry button (`<mux-uploader-retry>`) is not shown.

![image](https://github.com/muxinc/elements/assets/18343952/ea46153a-a788-4146-b137-2b712ecfaa8f)

Also when i modify HTML in inspector, showing the `<mux-uploader-retry>` button, clicking in doesn't reset `<mux-uploader-progress>` element state. This is screenshot after click the button:
![image](https://github.com/muxinc/elements/assets/18343952/c743f8bd-1d2a-4cc2-bc58-cce1484d4700)

### Expected Behavior

- `<mux-uploader-retry>` is shown, when upload fails. Allowing user to click the button.
- state of `<mux-uploader-progress>` is reseted after reseting uploader state (progress bar and percentage are hidden)

### What version of the package are you using?

1.0.0-beta.6

**Comment by cjpillsbury** [comment]
Thanks for filing the detailed issue and the handy screenshots. Our team's a bit stacked in our priority queue right now, but I'll be sure to keep you posted if/when we're able to make progress on this!

**Comment by cjpillsbury** [comment]
Hey @theazgra I'm hoping to be able to pick this up soon. Do you happen to know if this issue was unique to Windows+Edge, or does it show up on other browsers as well (windows or otherwise)?
