### ISSUE TITLE
Bug: All instanses of mux-video loaded if preload=none

### ISSUE THREAD

**Issue by quard8** [muxinc/elements#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video

### Which browsers are you using?

Safari, Safari on iOS

### Which operating systems are you using?

iOS

### Description

I have a carousel with videos and noticed the page crushes on Safari iOS/OSX with many videos. On Safari, <mux-video> started to load all metadata for each video, even if preload="none" was added to the mux-video tag. 

On Chrome, there is no problem; the video is loaded only then it appears on the screen. 

### Reduced test case

https://storistashop.myshopify.com/pages/mux-demo

### Steps to reproduce

1. Open Safari on OSX
2. Open https://storistashop.myshopify.com/pages/mux-demo
3. Open developers tools
4. Click on video
5. See a lot requests with .m3u8

On Safari iOS, after a few swipes, the page will be crushed and reloaded.

### Current Behavior

mux-video doesn't respect preload="none" on Safari

### Expected Behavior

mux-video respect preload="none" on Safari

### What version of the package are you using?

0.17.2

**Comment by cjpillsbury** [comment]
Hey @quard8, I'm having trouble reproducing this. I've created a simple codesandbox that is a fairly barebones case based on what you've described here: https://codesandbox.io/p/sandbox/mux-video-preload-behavior-22rvsg?file=%2Findex.html%3A18%2C18 
Are you able to reproduce in the sandbox? If not, is it possible you're setting some other properties/attributes that may be prompting the media to load, such as autoplay (which requires the media to load)?

**Comment by quard8** [comment]
Hi @cjpillsbury ! I see two requests in your example.

![Xnapper-2024-03-13-20 25 09](https://github.com/muxinc/elements/assets/318700/c8bb3041-3554-41ac-975b-242c6284a6aa)

In my example, you will see two requests multiplied by the number of videos. So, at some point, a page will crash on a mobile device.

**Comment by quard8** [comment]
@cjpillsbury any updates?

**Comment by cjpillsbury** [comment]
Hey @quard8 so sorry for the delay and the misunderstanding! You are 💯 right, playlists would load regardless of preload state. #916 should fix your situation, and describes the deep rabbit hole that you uncovered 😬. Hoping to get a release out ASAP!

**Comment by quard8** [comment]
Thank you very much! :)

**Comment by cjpillsbury** [comment]
Alright [@mux/mux-video@0.18.1](https://www.npmjs.com/package/@mux/mux-video/v/0.18.1) should be good to go and fix the issue! lmk if the problem persists for you though.
