### ISSUE TITLE
Feature Request: onCaptionsToggled

### ISSUE THREAD

**Issue by scmilee** [muxinc/elements#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player-react

### Description

Currently, we use video-js for our player and are looking to make the switch to the Mux player. It has all the current features we need except the ability for a callback to be passed in when captions are toggled on and off.

### Expected Behavior

It would be ideal to have a callback similar to `onRateChange` or `onPlay` that would either: 
Return a boolean value for captions activated or not.
Or
Return the track activated or undefined (when deactivated)

**Comment by cjpillsbury** [comment]
Hey @scmilee, having an easy to use in react event callback definitely sounds like a good idea/feature/improvement, given the acrobatics required for the refs. Our team has several things in the priority queue already, so not sure when we'll be able to get to this, but as a stopgap, let me know if this example of said acrobatics can hold you over in the interim: https://codesandbox.io/p/sandbox/gifted-david-vm71tz?file=%2Fsrc%2FApp.js
