### ISSUE TITLE
Bug: `@mux/mux-video-react` has type-error with latest version of `@types/react`

### ISSUE THREAD

**Issue by ryami333** [muxinc/elements#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react

### Which browsers are you using?

Other (add details below)

### Which operating systems are you using?

macOS

### Description

If you use the latest version of `@mux/mux-video-react` with the latest version of `@types/react` then you will always get a type error stating that `placeholder`, `onPointerEnterCapture` and `onPointerLeaveCapture` are mandatory props.

```
error TS2739: Type '{}' is missing the following properties from type 'Pick<Partial<Props>, "key" | "height" | "playsInline" | "poster" | "width" | "disablePictureInPicture" | "disableRemotePlayback" | "controls" | "controlsList" | ... 262 more ... | keyof MuxMediaPropTypes>': placeholder, onPointerEnterCapture, onPointerLeaveCapture

4   return <MuxVideoPlayer />;
```

### Steps to reproduce

1. Bump to the latest version of both packages. Eg. `yarn upgrade @mux/mux-video-react @types/react --latest`
2. Create a component file which uses `@mux/mux-video-react`, eg:
```tsx
import MuxVideoPlayer from "@mux/mux-video-react";

export function MyComponent() {
  return <MuxVideoPlayer />;
}
```
3. Perform typechecking: `yarn tsc`.

### Current Behavior

There are typescript errors when you omit the `placeholder`, `onPointerEnterCapture` and `onPointerLeaveCapture` props.

### Expected Behavior

There should be no typescript errors when you omit the `placeholder`, `onPointerEnterCapture` and `onPointerLeaveCapture` props.

### Errors

error TS2739: Type '{}' is missing the following properties from type 'Pick<Partial<Props>, "key" | "height" | "playsInline" | "poster" | "width" | "disablePictureInPicture" | "disableRemotePlayback" | "controls" | "controlsList" | ... 262 more ... | keyof MuxMediaPropTypes>': placeholder, onPointerEnterCapture, onPointerLeaveCapture

4   return <MuxVideoPlayer />;

### What version of the package are you using?

v0.8.5

**Comment by hipdev** [comment]
Yep, same issue in my case.

**Comment by luwes** [comment]
this was actually fixed in https://github.com/muxinc/elements/pull/897
double checked with canary
