### ISSUE TITLE
Bug: Clicking gray 'live' indicator in DVR mode does nto jump to live

### ISSUE THREAD

**Issue by dylanjha** [muxinc/elements#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player, mux-player-react

### Which browsers are you using?

Chrome

### Which operating systems are you using?

None

### Description

Clicking the "live" indicator when behind live in DVR mode does not jump to live.

I believe the intended behavior is that it should jump to live

### Steps to reproduce

1. Create a live stream
2. View in DVR mode
3. Seek to behind live, see the live indicator goes gray
4. Click live indicator, not jumping to live

See screen recording: https://drive.google.com/file/d/1o1_JZ3jG_ubEN46FxU3LdAQn9rxq4Ecm/view

### Current Behavior

See steps

### Expected Behavior

See steps

### What version of the package are you using?

v2.9.1

**Comment by vozalexander** [comment]
Following Mac browsers checked, same behaviour on all three:
Chrome Version 127.0.6533.120 (Official Build) (arm64).
Firefox 129.0.2 (64-bit)
Safari Version 17.4.1 (19618.1.15.11.14)

**Comment by cjpillsbury** [comment]
Will take a look at this asap.

**Comment by dylanjha** [comment]
Confirmed fixed in latest version. Thank you team @cjpillsbury & @luwes !
